<?php

namespace DoctrineORMModule\Proxy\__CG__\Procuracion\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Colarecepcion extends \Procuracion\Entity\Colarecepcion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'fechaentrada', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'horaentrada', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'sede', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'prioridad', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'lapiceroverde', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'turno', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'horaatencion', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'observaciones', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'razonsalida', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'idPersona', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'fechaentrada', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'horaentrada', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'sede', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'prioridad', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'lapiceroverde', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'turno', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'horaatencion', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'observaciones', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'razonsalida', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'idPersona', '' . "\0" . 'Procuracion\\Entity\\Colarecepcion' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Colarecepcion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaentrada($fechaentrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaentrada', [$fechaentrada]);

        return parent::setFechaentrada($fechaentrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaentrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaentrada', []);

        return parent::getFechaentrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraentrada($horaentrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraentrada', [$horaentrada]);

        return parent::setHoraentrada($horaentrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraentrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraentrada', []);

        return parent::getHoraentrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setSede($sede)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSede', [$sede]);

        return parent::setSede($sede);
    }

    /**
     * {@inheritDoc}
     */
    public function getSede()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSede', []);

        return parent::getSede();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridad($prioridad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridad', [$prioridad]);

        return parent::setPrioridad($prioridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridad', []);

        return parent::getPrioridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLapiceroverde($lapiceroverde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLapiceroverde', [$lapiceroverde]);

        return parent::setLapiceroverde($lapiceroverde);
    }

    /**
     * {@inheritDoc}
     */
    public function getLapiceroverde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLapiceroverde', []);

        return parent::getLapiceroverde();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurno($turno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurno', [$turno]);

        return parent::setTurno($turno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurno', []);

        return parent::getTurno();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraatencion($horaatencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraatencion', [$horaatencion]);

        return parent::setHoraatencion($horaatencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraatencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraatencion', []);

        return parent::getHoraatencion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonsalida($razonsalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonsalida', [$razonsalida]);

        return parent::setRazonsalida($razonsalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonsalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonsalida', []);

        return parent::getRazonsalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPersona(\Procuracion\Entity\Persona $idPersona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPersona', [$idPersona]);

        return parent::setIdPersona($idPersona);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPersona', []);

        return parent::getIdPersona();
    }

}
