<?php

namespace DoctrineORMModule\Proxy\__CG__\Procuracion\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visita extends \Procuracion\Entity\Visita implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'fechaentrada', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'horaentrada', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'sede', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'institucion', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'tipoinstitucion', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'motivovisita', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'fechasalida', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'horasalida', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'notaalsalir', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'llamadasrealizadas', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'createdBy', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'createdAt', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'updatedAt', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'idPersona', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'empleado'];
        }

        return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'fechaentrada', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'horaentrada', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'sede', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'institucion', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'tipoinstitucion', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'motivovisita', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'fechasalida', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'horasalida', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'notaalsalir', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'llamadasrealizadas', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'createdBy', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'createdAt', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'updatedAt', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'idPersona', '' . "\0" . 'Procuracion\\Entity\\Visita' . "\0" . 'empleado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Visita $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaentrada($fechaentrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaentrada', [$fechaentrada]);

        return parent::setFechaentrada($fechaentrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaentrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaentrada', []);

        return parent::getFechaentrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraentrada($horaentrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraentrada', [$horaentrada]);

        return parent::setHoraentrada($horaentrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraentrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraentrada', []);

        return parent::getHoraentrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setSede($sede)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSede', [$sede]);

        return parent::setSede($sede);
    }

    /**
     * {@inheritDoc}
     */
    public function getSede()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSede', []);

        return parent::getSede();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpleado($empleado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpleado', [$empleado]);

        return parent::setEmpleado($empleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpleado', []);

        return parent::getEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstitucion($institucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstitucion', [$institucion]);

        return parent::setInstitucion($institucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstitucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstitucion', []);

        return parent::getInstitucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoinstitucion($tipoinstitucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoinstitucion', [$tipoinstitucion]);

        return parent::setTipoinstitucion($tipoinstitucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoinstitucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoinstitucion', []);

        return parent::getTipoinstitucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivovisita($motivovisita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivovisita', [$motivovisita]);

        return parent::setMotivovisita($motivovisita);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivovisita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivovisita', []);

        return parent::getMotivovisita();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechasalida($fechasalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechasalida', [$fechasalida]);

        return parent::setFechasalida($fechasalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechasalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechasalida', []);

        return parent::getFechasalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasalida($horasalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasalida', [$horasalida]);

        return parent::setHorasalida($horasalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasalida', []);

        return parent::getHorasalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotaalsalir($notaalsalir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotaalsalir', [$notaalsalir]);

        return parent::setNotaalsalir($notaalsalir);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaalsalir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaalsalir', []);

        return parent::getNotaalsalir();
    }

    /**
     * {@inheritDoc}
     */
    public function setLlamadasRealizadas($llamadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLlamadasRealizadas', [$llamadas]);

        return parent::setLlamadasRealizadas($llamadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getLlamadasRealizadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLlamadasRealizadas', []);

        return parent::getLlamadasRealizadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPersona(\Procuracion\Entity\Persona $idPersona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPersona', [$idPersona]);

        return parent::setIdPersona($idPersona);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPersona', []);

        return parent::getIdPersona();
    }

}
