<?php

namespace DoctrineORMModule\Proxy\__CG__\Procuracion\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Expediente extends \Procuracion\Entity\Expediente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'numero', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'hechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'lugarhechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'fechahechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'peticion', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'pruebas', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'fechaingreso', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'tipoagresion', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'reportadoen', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'area', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'deptohechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'munihechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'reportadoanteriormente', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idCola', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idSede', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idTipo', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'correlativo', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'anio', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'updated_at', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'updated_by'];
        }

        return ['__isInitialized__', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'id', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'numero', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'hechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'lugarhechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'fechahechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'peticion', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'pruebas', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'fechaingreso', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'tipoagresion', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'reportadoen', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'area', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'deptohechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'munihechos', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'reportadoanteriormente', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idCola', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idSede', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'idTipo', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'correlativo', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'anio', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'updated_at', '' . "\0" . 'Procuracion\\Entity\\Expediente' . "\0" . 'updated_by'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Expediente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setHechos($hechos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHechos', [$hechos]);

        return parent::setHechos($hechos);
    }

    /**
     * {@inheritDoc}
     */
    public function getHechos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHechos', []);

        return parent::getHechos();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarhechos($lugarhechos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarhechos', [$lugarhechos]);

        return parent::setLugarhechos($lugarhechos);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarhechos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarhechos', []);

        return parent::getLugarhechos();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahechos($fechahechos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahechos', [$fechahechos]);

        return parent::setFechahechos($fechahechos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahechos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahechos', []);

        return parent::getFechahechos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeticion($peticion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeticion', [$peticion]);

        return parent::setPeticion($peticion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeticion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeticion', []);

        return parent::getPeticion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPruebas($pruebas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPruebas', [$pruebas]);

        return parent::setPruebas($pruebas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPruebas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPruebas', []);

        return parent::getPruebas();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', [$fechaingreso]);

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', []);

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoagresion($tipoagresion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoagresion', [$tipoagresion]);

        return parent::setTipoagresion($tipoagresion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoagresion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoagresion', []);

        return parent::getTipoagresion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRerortadoen($reportadoen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRerortadoen', [$reportadoen]);

        return parent::setRerortadoen($reportadoen);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportadoen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportadoen', []);

        return parent::getReportadoen();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea(\Procuracion\Entity\DetalleCatalogo $area = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', [$area]);

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeptohechos(\Procuracion\Entity\Departamento $deptohechos = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeptohechos', [$deptohechos]);

        return parent::setDeptohechos($deptohechos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeptohechos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeptohechos', []);

        return parent::getDeptohechos();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunihechos(\Procuracion\Entity\Municipio $munihechos = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunihechos', [$munihechos]);

        return parent::setMunihechos($munihechos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunihechos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunihechos', []);

        return parent::getMunihechos();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportadoanteriormente(\Procuracion\Entity\DetalleCatalogo $reportadoanteriormente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportadoanteriormente', [$reportadoanteriormente]);

        return parent::setReportadoanteriormente($reportadoanteriormente);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportadoanteriormente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportadoanteriormente', []);

        return parent::getReportadoanteriormente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCola(\Procuracion\Entity\ColaRecepcion $idCola = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCola', [$idCola]);

        return parent::setIdCola($idCola);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCola', []);

        return parent::getIdCola();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSede(\Procuracion\Entity\Sede $idSede = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSede', [$idSede]);

        return parent::setIdSede($idSede);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSede()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSede', []);

        return parent::getIdSede();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipo(\Procuracion\Entity\TipoExpediente $idTipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipo', [$idTipo]);

        return parent::setIdTipo($idTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipo', []);

        return parent::getIdTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrelativo($correlativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrelativo', [$correlativo]);

        return parent::setCorrelativo($correlativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrelativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrelativo', []);

        return parent::getCorrelativo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnio($anio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnio', [$anio]);

        return parent::setAnio($anio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', []);

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\Procuracion\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$usuario]);

        return parent::setUpdatedBy($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

}
