<section class="content-header">
    <h1><?php echo $this->title; ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $this->subtitle; ?></h3>
                </div>
                <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttributes(array(
                    'action' => $this->url('recepcion/procesar', array('action' => 'resultado')),
                    'method' => 'post'
                ));
                // Get the form label plugin
                $formLabel = $this->plugin('formLabel');
                // Render the opening tag
                echo $this->form()->openTag($form);
                ?>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="form-group">
                                <?php
                                $numdoc = $form->get('numdoc');
                                echo $formLabel->openTag() . $numdoc->getOption('label') . " ";
                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($numdoc);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group">
                                <?php
                                $nombre = $form->get('nombre');
                                echo $formLabel->openTag() . $nombre->getOption('label') . " ";
                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($nombre);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group">
                                <?php
                                $apellido = $form->get('apellido');
                                echo $formLabel->openTag() . $apellido->getOption('label') . " ";
                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($apellido);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <?php echo $this->formElement($form->get('buscar')) ?>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/solicitante" tooltip="Solicitante">
        </a>
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/visitante" tooltip="Visitante">
        </a>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header danger">
                <h4 class="modal-title text-danger">Atención</h4>
            </div>
            <div class="modal-body">
                <p class="text-center">Debe ingresar al menos un criterio de búsqueda</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger btn-flat" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('form').submit(function() {
        var numdoc = $.trim($('input[name="numdoc"]').val()),
                nombre = $.trim($('input[name="nombre"]').val()),
                apellido = $.trim($('input[name="apellido"]').val());
        if (numdoc === '' && nombre === '' && apellido === '') {
            $('#alertModal').modal('show');
            return false;
        }
    });
</script>
