<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Busqueda de registros</h3>
                </div>
                <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttributes(array(
                    'action' => $this->url('recepcion', array('action' => 'resultado')),
                    'method' => 'post'
                ));
                // Get the form label plugin
                $formLabel = $this->plugin('formLabel');
                // Render the opening tag
                echo $this->form()->openTag($form);
                ?>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-8">
                            <div class="alert alert-info alert-dismissible">
                                <h4><i class="icon fa fa-info"></i>¡Atención!</h4>
                                Para realizar una busqueda de registros debe especificar un rango de fechas.
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="form-group">
                                <?php
                                $fechaInicio = $form->get('fecha')->setAttributes(array('name' => 'fechaInicio', 'required' => true, 'readonly' => false, 'id' => 'datepicker1'));
                                echo $formLabel->openTag() . $fechaInicio->getOption('label') . " inicial";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechaInicio);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group">
                                <?php
                                $fechaFin = $form->get('fecha')->setAttributes(array('name' => 'fechaFin', 'required' => true, 'readonly' => false, 'id' => 'datepicker2'));
                                echo $formLabel->openTag() . $fechaFin->getOption('label') . " final";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechaFin);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-4"></div>
                    </div>
                </div>
                <div class="box-footer">
                    <?php echo $this->formElement($form->get('buscar')) ?>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/solicitante" tooltip="Solicitante">
        </a>
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/visitante" tooltip="Visitante">
        </a>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header danger">
                <h4 class="modal-title text-danger">Atención</h4>
            </div>
            <div class="modal-body">
                <p class="text-center">Debe ingresar al menos un criterio de búsqueda</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger btn-flat" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    /*$('form').submit(function() {
     var numdoc = $.trim($('input[name="numdoc"]').val()),
     nombre = $.trim($('input[name="nombre"]').val()),
     apellido = $.trim($('input[name="apellido"]').val());
     if (numdoc === '' && nombre === '' && apellido === '') {
     $('#alertModal').modal('show');
     return false;
     }
     });*/
    $(function() {
        $("#datepicker1, #datepicker2").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'});
    });
</script>
