<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Cambiar tipo</h3>
                </div>
                <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttributes(array(
                    'action' => $this->url('recepcion/procesar', array('action' => 'actualizar')),
                    'method' => 'post'
                ));
                // Get the form label plugin
                $formLabel = $this->plugin('formLabel');
                // Render the opening tag
                echo $this->form()->openTag($form);
                ?>

                <div class="box-body">
                    <?php if ($this->tipo == 'solicitud') { ?>
                        <?php
                        $tipo = $form->get('tipopersona')->setValue('visitante');
                        $pid = $form->get('pid')->setValue($cola->getIdpersona()->getId());
                        $id = $form->get('id')->setValue($cola->getId());
                        echo $this->formInput($tipo);
                        echo $this->formInput($pid);
                        echo $this->formInput($id);
                        ?>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <?php
                                    $fecha = $form->get('fecha')->setValue($cola->getFechaentrada()->format("Y-m-d"));
                                    echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($fecha);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <?php
                                    $hora = $form->get('hora')->setValue($cola->getHoraentrada()->format("H:m:s"));
                                    echo $formLabel->openTag() . $hora->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($hora);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $tipodoc = $form->get('tipodoc')->setValue($cola->getIdpersona()->getTipoDocumento());
                                    echo $formLabel->openTag() . $tipodoc->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formSelect($tipodoc);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $numdoc = $form->get('numdoc')->setValue($cola->getIdpersona()->getNumeroDocumento());
                                    echo $formLabel->openTag() . $numdoc->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($numdoc);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    if (($cola->getIdpersona()->getFechanacimiento()) == NULL) {
                                        $fecha_nac = $form->get('nac')->setValue($cola->getIdpersona()->getFechanacimiento());
                                    } else {
                                        $fecha_nac = $form->get('nac')->setValue($cola->getIdpersona()->getFechanacimiento()->format("d/m/Y"));
                                    }
                                    echo $formLabel->openTag() . $fecha_nac->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($fecha_nac);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $sexo = $form->get('sexo')->setValue($cola->getIdpersona()->getSexo());
                                    echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . " ";
                                    echo $formLabel->closeTag() . "</p>";
                                    echo $this->formRadio($sexo);
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $nombre = $form->get('nombre')->setValue($cola->getIdpersona()->getNombres());
                                            echo $formLabel->openTag() . $nombre->getOption('label') . " ";
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($nombre);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $apellido = $form->get('apellido')->setValue($cola->getIdpersona()->getApellidos());
                                            echo $formLabel->openTag() . $apellido->getOption('label') . " ";
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($apellido);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $institucion = $form->get('institucion');
                                            echo $formLabel->openTag() . $institucion->getOption('label') . " ";
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($institucion);
                                            ?>
                                        </div>

                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $empleados = $this->empleados;
                                            $empleadosOptions = array();
                                            foreach ($empleados as $empleadoOption) {
                                                $empleadosOptions[$empleadoOption->getId()] = $empleadoOption->getNombres() . " " . $empleadoOption->getApellidos();
                                            }
                                            $empleado = $form->get('empleado')->setValueOptions($empleadosOptions);
                                            echo $formLabel->openTag() . $empleado->getOption('label') . " ";

                                            //echo $this->formElementErrors($name);
                                            echo $formLabel->closeTag();
                                            echo $this->formSelect($empleado);
                                            ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group ">
                                    <?php
                                    $motivo = $form->get('motivo');
                                    echo $formLabel->openTag() . $motivo->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formTextarea($motivo);
                                    ?>
                                </div>

                            </div>
                        </div>
                    <?php } else { ?>
                        <?php
                        $tipo = $form->get('tipopersona')->setValue('solicitante');
                        $pid = $form->get('pid')->setValue($visita->getIdpersona()->getId());
                        $id = $form->get('id')->setValue($visita->getId());
                        echo $this->formInput($tipo);
                        echo $this->formInput($pid);
                        echo $this->formInput($id);
                        ?>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <?php
                                    $fecha = $form->get('fecha')->setValue($visita->getFechaentrada()->format("Y-m-d"));
                                    echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($fecha);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <?php
                                    $hora = $form->get('hora')->setValue($visita->getHoraentrada()->format("H:m:s"));
                                    echo $formLabel->openTag() . $hora->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($hora);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $tipodoc = $form->get('tipodoc')->setValue($visita->getIdpersona()->getTipoDocumento());
                                    echo $formLabel->openTag() . $tipodoc->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formSelect($tipodoc);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $numdoc = $form->get('numdoc')->setValue($visita->getIdpersona()->getNumeroDocumento());
                                    echo $formLabel->openTag() . $numdoc->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($numdoc);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    if (($visita->getIdpersona()->getFechanacimiento()) == NULL) {
                                        $fecha_nac = $form->get('nac')->setValue($visita->getIdpersona()->getFechanacimiento());
                                    } else {
                                        $fecha_nac = $form->get('nac')->setValue($visita->getIdpersona()->getFechanacimiento()->format("d/m/Y"));
                                    }
                                    echo $formLabel->openTag() . $fecha_nac->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formInput($fecha_nac);
                                    ?>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="form-group">
                                    <?php
                                    $sexo = $form->get('sexo')->setValue($visita->getIdpersona()->getSexo());
                                    echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . " ";
                                    echo $formLabel->closeTag() . "</p>";
                                    echo $this->formRadio($sexo);
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $nombre = $form->get('nombre')->setValue($visita->getIdpersona()->getNombres());
                                            echo $formLabel->openTag() . $nombre->getOption('label') . " ";
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($nombre);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $apellido = $form->get('apellido')->setValue($visita->getIdpersona()->getApellidos());
                                            echo $formLabel->openTag() . $apellido->getOption('label') . " ";
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($apellido);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $lgbti = $form->get('lgbti');
                                            echo "<p>" . $formLabel->openTag() . $lgbti->getOption('label');
                                            echo $formLabel->closeTag() . "</p>";
                                            echo $this->formRadio($lgbti);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="form-group">
                                            <?php
                                            $prioridad = $form->get('prioridad');
                                            echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                            echo $formLabel->closeTag() . "</p>";
                                            echo $this->formRadio($prioridad);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <?php
                                        $lapiceroverde = $form->get('lapiceroverde');
                                        echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                        echo $formLabel->closeTag() . "</p>";
                                        echo $this->formRadio($lapiceroverde);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group ">
                                    <?php
                                    $obs = $form->get('obs');
                                    echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                    echo $formLabel->closeTag();
                                    echo $this->formTextarea($obs);
                                    ?>
                                </div>

                            </div>
                        </div>
                        <?php
                    }
                    ?>
                    <div class="box-footer">
                        <?php echo $this->formElement($form->get('guardar')->setValue('Modificar')) ?>
                        <?php
                        if ($this->tipo == 'solicitud') {
                            echo "<a href='" . $this->url('recepcion') . "/cola' class='btn btn-danger'>Cancelar</a>";
                        } else {
                            echo "<a href='" . $this->url('recepcion') . "/visita' class='btn btn-danger'>Cancelar</a>";
                        }
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $("#numdoc").autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: "<?php echo $this->basePath(); ?>/validacion/validardpi",
                    dataType: "json",
                    type: "POST",
                    data: {
                        term: request.term
                    },
                    success: function(data) {
                        response($.map(data, function(item) {
                            return {
                                label: item,
                                value: item
                            };
                        }));
                    }
                    /*error: function(a, b, c) {
                     debugger;
                     }*/
                });

            }
        });
        $("#numdoc").focusout(function() {
            $.ajax({
                url: "<?php echo $this->basePath(); ?>/validacion/seleccionardpi",
                dataType: "json",
                type: "POST",
                data: {
                    term: $("#numdoc").val()
                },
                success: function(data) {
                    $('#id').val(data[0]);
                    $('#tipodoc').val(data[1]);
                    $('#datepicker').val(data[2]);
                    //$('#sexo').val(data[3]);
                    $('#nombres').val(data[4]);
                    $('#apellidos').val(data[5]);

                    var $radios = $('input:radio[name=sexo]');
                    if ($radios.is(':checked') === false) {
                        $radios.filter('[value=' + data[3] + ']').prop('checked', true);
                    }

                },
                error: function() {
                    $('#id').val();
                    $('#tipodoc').val();
                    $('#datepicker').val();
                    //$('#sexo').val(data[3]);
                    $('#nombres').val();
                    $('#apellidos').val();
                }
            });
            if ($("#numdoc").val() !== '') {
                $("#tipodoc").attr("required", "true");
            }
        });
    });

</script>
