<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-warning">
                <div class="box-header">
                    <h3 class="box-title">Cola de solicitantes</h3>
                </div>
                <div class="box-body">
                    <table id="datatable" class="table table-bordered table-hover dataTable" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Turno</th>
                                <th>DP</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Hora</th>
                                <th>Observaciones</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $colas = $this->cola;
                            foreach ($colas as $cola):
                                switch ($cola->getPrioridad()) {
                                    case '1':
                                        $class = "red-text";
                                        $tooltip = "Urgente";
                                        break;
                                    case '2':
                                        $class = "yellow-text";
                                        $tooltip = "Importante";
                                        break;
                                    case '3':
                                        $class = "green-text";
                                        $tooltip = "Normal";
                                }
                                ?>
                                <tr>
                                    <td>
                                        <a data-toggle="tooltip" title="<?php echo $tooltip ?>">
                                            <span class="glyphicon glyphicon-exclamation-sign <?php echo $class ?> fa-lg">
                                            </span>
                                        </a><strong><?php echo $cola->getTurno(); ?></strong>
                                    </td>
                                    <td>
                                        <?php
                                        switch ($cola->getLapiceroverde()) {
                                            case '1':
                                                $lv = "SI";
                                                break;
                                            case '0':
                                                $lv = "NO";
                                                break;
                                            default :
                                                $lv = "NO";
                                        }
                                        echo $lv;
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getIdpersona()->getNombres(); ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getIdpersona()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getFechaentrada()->format("H:i:s"); ?>

                                    </td>
                                    <td>
                                        <?php echo $cola->getObservaciones(); ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'detallecola', 'id' => $cola->getId())); ?>" data-toggle="modal" data-target="#detailsModal" data-tt="tooltip" title="Detalles">
                                            <span class="glyphicon glyphicon-search fa-lg"></span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'editarcola', 'id' => $cola->getId())); ?>"  data-tt="tooltip" title="Editar">
                                            <span class="glyphicon glyphicon-edit orange-text fa-lg"></span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'atender', 'id' => $cola->getId())); ?>" data-toggle="tooltip" title="Atender" >
                                            <span class="glyphicon glyphicon-log-in green-text fa-lg"></span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'salidacola', 'id' => $cola->getId())); ?>" data-toggle="modal" data-target="#departureModal" data-tt="tooltip" title="Salida">
                                            <span class="glyphicon glyphicon-log-out red-text fa-lg"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <?php
        $permisos = $this->permisos;
        foreach ($permisos as $permiso) {
            echo "<a class='fab-button bg-primary' href=" . $this->url('solicitud') . "/registro/" . $permiso["accion"] . "' tooltip='" . $permiso["accion"] . "'>";
            foreach ($permiso["permiso"] as $perm) {
                print_r($perm);
                echo "<br>";
            }
        }
        ?>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>

    <!--<button class="btn-default btn-floating btn-large waves-effect waves-light"><span class="glyphicon glyphicon-plus"></span></button>
    <ul>
        <li><a href="<?php /* echo $this->url('formulario') */ ?>registrovisita"><span class="glyphicon glyphicon-user"></span></a></li>
    </ul>-->
</div>



<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<div class="modal fade" id="departureModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({
            "columnDefs": [
                {"width": "10%", "targets": 6}
            ]
        });
    });
</script>