<meta http-equiv="refresh" content="30"/>
<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-warning">
                <div class="box-header">
                    <h3 class="box-title">Cola de solicitantes</h3>
                </div>
                <div class="box-body">
                    <table id="datatable" class="table table-bordered table-hover table-responsive dataTable" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Turno</th>
                                <th>DP</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Hora</th>
                                <th>Observaciones</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $colas = $this->cola;
                            $i = 0;
                            foreach ($colas as $cola):
                                switch ($cola->getPrioridad()) {
                                    case '1':
                                        $class = "red-text";
                                        $tooltip = "Urgente";
                                        break;
                                    case '2':
                                        $class = "yellow-text";
                                        $tooltip = "Importante";
                                        break;
                                    case '3':
                                        $class = "green-text";
                                        $tooltip = "Normal";
                                }
                                ?>
                                <tr>
                                    <td>
                                        <a data-toggle="tooltip" title="<?php echo $tooltip ?>">
                                            <span class="glyphicon glyphicon-exclamation-sign <?php echo $class ?> fa-lg">
                                            </span>
                                        </a><strong><?php echo $cola->getTurno(); ?></strong>
                                    </td>
                                    <td>
                                        <?php
                                        switch ($cola->getLapiceroverde()) {
                                            case '1':
                                                $lv = "SI";
                                                break;
                                            case '0':
                                                $lv = "NO";
                                                break;
                                            default :
                                                $lv = "NO";
                                        }
                                        echo $lv;
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getIdpersona()->getNombres(); ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getIdpersona()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $cola->getFechaentrada()->format("H:i:s"); ?>

                                    </td>
                                    <td>
                                        <?php
                                        $string = strip_tags($cola->getObservaciones());
                                        if (strlen($string) > 95) {
                                            // truncate string
                                            $stringCut = substr($string, 0, 95);
                                            // make sure it ends in a word so assassinate doesn't become ass...
                                            $string = substr($stringCut, 0, strrpos($stringCut, ' ')) . '... <small class="text-muted"><em>ver detalle</em></small>';
                                        }
                                        echo $string;
                                        ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'detallecola', 'id' => $cola->getId())); ?>" data-toggle="modal" data-target="#detailsModal">
                                            <span class="badge bg-blue">Detalle</span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'editarcola', 'id' => $cola->getId())); ?>">
                                            <span class="badge bg-orange">Editar</span>
                                        </a>

                                        <a href="<?php echo $this->url('recepcion', array('action' => 'salidacola', 'id' => $cola->getId())); ?>" data-toggle="modal" data-target="#departureModal">
                                            <span class="badge bg-red">Retirar</span>
                                        </a>
                                        <?php
                                        if ($i == 0) {
                                            $linkclass = "bg-green";
                                            echo "<a href='" . $this->url('recepcion', array('action' => 'atender', 'id' => $cola->getId())) . "'>"
                                            . "<span class='badge " . $linkclass . "'>Atender</span>"
                                            . "</a>";
                                            //$link = $this->url('recepcion', array('action' => 'atender', 'id' => $cola->getId()));
                                        } else {
                                            /* $link = "#";
                                              $linkclass = "bg-gray"; */
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!--fab-button-add-->
<div class="fixed-action-btn">
    <nav class="fab">
        <?php
        $permisos = $this->permisos;
        foreach ($permisos as $permiso) {
            foreach ($permiso["permiso"] as $perm) {
                if ($perm == 11) {
                    echo "<a class='fab-button bg-primary " . $permiso["accion"] . "' href='" . $this->url('recepcion', array('action' => 'registro', 'id' => $permiso["accion"])) . "' data-tip='tooltip' title='" . ucfirst($permiso["accion"]) . "'>";
                }
            }
        }
        ?>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<div class="modal fade" id="departureModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({
            "bSort": false
        });
    });
</script>