<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Consulta de expedientes</h3>
                </div>
                <div class="box-body">
                    <table id="datatable">
                        <thead>
                            <tr>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!--fab-button-add-->
<div class="fixed-action-btn">
    <nav class="fab">
        <?php
        $permisos = $this->permisos;
        foreach ($permisos as $permiso) {
            foreach ($permiso["permiso"] as $perm) {
                if ($perm == 11) {
                    echo "<a class='fab-button bg-primary " . $permiso["accion"] . "' href='" . $this->url('recepcion', array('action' => 'registro', 'id' => $permiso["accion"])) . "' data-tip='tooltip' title='" . ucfirst($permiso["accion"]) . "'>";
                }
            }
        }
        ?>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>


