<section class="content-header">
    <h1><?php echo $this->title; ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $this->subtitle_visitas; ?></h3>
                </div>
                <div class="box-body">
                    <table id="datatable-visitas" class="table table-bordered table-hover dataTable" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Fecha <small>(Ingreso)</small></th>
                                <th>Hora <small>(Ingreso)</small></th>
                                <th>Motivo</th>
                                <th>Empleado</th>
                                <th>Unidad</th>
                                <th>Fecha <small>(Salida)</small></th>
                                <th>Hora <small>(Salida)</small></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $visitas = $this->visitas;
                            foreach ($visitas as $visita):
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $visita->getFechaentrada()->format("d/m/Y"); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getHoraentrada()->format("H:i:s"); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getMotivovisita(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getEmpleado()->getNombres() . " " . $visita->getEmpleado()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getEmpleado()->getUnidadadministrativa()->getNombre(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getFechasalida()->format("H:i:s"); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getHorasalida()->format("H:i:s"); ?>
                                    </td>

                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $this->subtitle_solicitudes; ?></h3>
                </div>
                <div class="box-body">
                    <table id="datatable-solicitudes" class="table table-bordered table-hover dataTable" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Fecha <small>(Ingreso)</small></th>
                                <th>Hora <small>(Ingreso)</small></th>
                                <th>Prioridad</th>
                                <th>Turno</th>
                                <th>Lapicero Verde</th>
                                <th>Hora <small>(Atención)</small></th>
                                <th>Observaciones </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $solicitudes = $this->solicitudes;
                            foreach ($solicitudes as $solicitud):
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $solicitud->getFechaentrada()->format("d/m/Y"); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getHoraentrada()->format("H:i:s"); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getPrioridad(); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getTurno(); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getLapiceroverde(); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getHoraatencion(); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getObservaciones(); ?>
                                    </td>

                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/solicitante" tooltip="Solicitante">
        </a>
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/visitante" tooltip="Visitante">
        </a>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable-visitas').DataTable({
            "language": {
                "url": "<?php echo $this->basePath(); ?>/js/datatables/spanish.json"
            },
            "bSort": false
        });
        $('#datatable-solicitudes').DataTable({
            "language": {
                "url": "<?php echo $this->basePath(); ?>/js/datatables/spanish.json"
            },
            "bSort": false
        });
    });
</script>





