<?php $visita = $this->visita; ?>
<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Detalle de visita</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-3">
                            <strong>Tipo de documento</strong>
                            <p><?php echo $visita->getIdpersona()->getTipoDocumento(); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong># de documento</strong>
                            <p><?php echo $visita->getIdpersona()->getNumeroDocumento(); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong>Nombres</strong>
                            <p><?php echo $visita->getIdpersona()->getNombres(); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong>Apellidos</strong>
                            <p><?php echo $visita->getIdpersona()->getApellidos(); ?></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-3">
                            <strong>Fecha</strong>
                            <p><?php echo $visita->getFechaentrada()->format("d/m/Y"); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong>Hora</strong>
                            <p><?php echo $visita->getFechaentrada()->format("H:i:s"); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong>Empresa / Institucion</strong>
                            <p><?php echo $visita->getInstitucion(); ?></p>
                        </div>
                        <div class="col-xs-3">
                            <strong>Motivo</strong>
                            <p><?php echo $visita->getMotivoVisita(); ?></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <strong>Empleado</strong>
                            <p><?php echo $visita->getEmpleado()->getNombres() . " " . $visita->getEmpleado()->getApellidos(); ?></p>
                        </div>
                        <div class="col-xs-6">
                            <strong>Oficina</strong>
                            <p><?php echo $visita->getEmpleado()->getUnidadadministrativa()->getNombre(); ?></p>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button class="btn btn-danger btn-flat" data-dismiss="modal">Cerrar</button>


                </div>
            </div>
        </div>
    </div>
</section>



