<?php
$expediente = $this->expediente["datos"];
$cola = $expediente->getIdCola();
$persona = $this->expediente["persona"];
$calificacion = $this->expediente["calificacion"];
?>

<section class="content-header">
    <h1>Investigación #<?php echo $expediente->getNumero(); ?></h1>
    <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Hechos / Calificación) Etapa 1 de 3</span>
        </div>
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>( / ) Etapa 2 de 3</span>
        </div>
    </div>
</section>
<section class="content">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url('recepcion', array('action' => 'guardarinvestigacion')),
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    $formLabel = $this->plugin('formLabel');

    $idcola = $form->get('id')->setValue($cola->getId())->setAttributes(array("name" => "idcola"));
    echo $this->formInput($idcola);

    $id = $form->get('id')->setValue($expediente->getId())->setAttributes(array("name" => "idexpediente", "disabled" => true));
    echo $this->formInput($id);

    $idexpediente = $form->get('id')->setValue($expediente->getId())->setAttributes(array("name" => "ide", "disabled" => false));
    echo $this->formInput($idexpediente);

    $idpersona = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array("name" => "idpersona", "disabled" => true));
    echo $this->formInput($idpersona);

    $idp = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array("name" => "idp", "disabled" => false));
    echo $this->formInput($idp);
    ?>

    <div class="row">
        <div class = "col-xs-12">
            <!------------- Inicia formulario solicitud ----------------->
            <div class = "box box-default color-palette-box collapsed-box">
                <div class = "box-header with-border">
                    <i class = "fa fa-file"></i>
                    <h3 class = "box-title">Solicitud
                        <small>
                            <?php
                            echo " / " . $cola->getFechaentrada()->format("d/m/Y H:i:s");
                            switch ($cola->getPrioridad()) {
                                case '1':
                                    $class = "red-text";
                                    $prioridad = "Urgente";
                                    break;
                                case '2':
                                    $class = "yellow-text";
                                    $prioridad = "Importante";
                                    break;
                                case '3':
                                    $class = "green-text";
                                    $prioridad = "Normal";
                            }
                            echo " / " . $prioridad;
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class = "box-body">
                    <div class = "row">
                        <div class = "col-xs-12">
                            <div class="form-group">
                                <?php
                                $fechasol = $form->get('fecha')->setValue($cola->getFechaentrada()->format("d/m/Y H:i:s"))->setAttributes(array(
                                    "name" => "fechasol",
                                    "type" => "text",
                                    "class" => "form-control datepicker",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $fechasol->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechasol);
                                ?>

                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $prioridad = $form->get('prioridad')->setValue($cola->getPrioridad())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($prioridad);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $lapiceroverde = $form->get('lapiceroverde')->setValue($cola->getLapiceroverde())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($lapiceroverde);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $obs = $form->get('obs')->setValue($cola->getObservaciones())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($obs);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!------------- Finaliza formulario solicitud ----------------->
        </div>
    </div>
    <div class="row" id="hechos">
        <div class="col-xs-12">
            <!------------- Inicia formulario hechos ----------------->
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-calendar"></i>
                    <h3 class="box-title">Hechos y Calificación
                        <small>
                            <?php
                            echo " / " . $expediente->getFechahechos()->format("d/m/Y");
                            echo " / " . $expediente->getDeptohechos()->getNombre();
                            echo " / " . $expediente->getMunihechos()->getNombre();
                            echo " / " . ucwords(strtolower($expediente->getIdTipo()->getTipo()));
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $fecha = $form->get('fechahecho')->setValue($expediente->getFechahechos()->format("d/m/Y"))->setAttributes(array(
                                    "class" => "form-control datepicker",
                                    "name" => "hechos_fecha",
                                    "readonly" => false,
                                    "disabled" => true,
                                    "required" => true
                                ));
                                echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $area = $form->get('areaubicacion')->setValue($expediente->getArea())->setAttributes(array(
                                    "name" => "hechos_ubicacion",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $area->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($area);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $direccion = $form->get('direccion')->setValue($expediente->getLugarhechos())->setAttributes(array(
                                    "name" => "hechos_direccion",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $direccion->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($direccion);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $deptos = $this->deptos;
                                $deptosOptions = array();
                                foreach ($deptos as $deptoOption) {
                                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                }
                                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($expediente->getDeptohechos()->getCodigo())->setAttributes(array(
                                    "name" => "hechos_depto",
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($depto);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $munis = $this->munis;
                                //print_r($munis);
                                $munisOptions = array();
                                foreach ($munis as $muniOption) {
                                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                }
                                $muni = $form->get('muni')->setValueOptions($munisOptions)->setValue($expediente->getMunihechos()->getCodigo())->setAttributes(array(
                                    "name" => "hechos_muni",
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($muni);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $hechos = $form->get('deschechos')->setValue($expediente->getHechos())->setAttributes(array(
                                    "id" => "hechos",
                                    "name" => "hechos_descripcion",
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $hechos->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($hechos);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $peticion = $form->get('peticion')->setValue($expediente->getPeticion())->setAttributes(array(
                                    "name" => "hechos_peticion",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $peticion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($peticion);
                                ?>
                            </div>
                        </div>
                        <div class = "col-xs-6">
                            <div class="form-group">
                                <?php
                                $pruebas = $form->get('pruebas')->setValue($expediente->getPruebas())->setAttributes(array(
                                    "name" => "hechos_pruebas",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $pruebas->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($pruebas);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $tipoexpediente = $form->get('tipoexpediente')->setValue($expediente->getIdTipo()->getId())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $tipoexpediente->getOption('label') . "  &nbsp;" . $formLabel->closeTag();
                                echo $this->formRadio($tipoexpediente);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12 calificacion">
                            <strong>Hechos violatorios</strong>
                            <ul>
                                <?php
                                foreach ($calificacion as $hecho) {
                                    echo "<li>" . $hecho->getIdHecho()->getHecho() . "</li>";
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="col-xs-12 calificacion" style="display: none">
                            <div class="row" id="calificacion">
                                <div class="col-xs-3">
                                    <h4>Civíles y Políticos</h4>
                                    <div class="form-group">
                                        <?php
                                        $derechos = $this->derechos;
                                        foreach ($derechos as $derechoOption) {
                                            if ($derechoOption->getArea() == "DCP") {
                                                $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                                echo "<div class='checkbox'>";
                                                echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                                echo $derechoOption->getDerecho() . "</label></div>";
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Económicos, Sociales y Culturales</h4>
                                    <div class="form-group checkdiv">
                                        <?php
                                        foreach ($derechos as $derechoOption) {
                                            if ($derechoOption->getArea() == "DESC") {
                                                $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                                echo "<div class='checkbox'>";
                                                echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                                echo $derechoOption->getDerecho() . "</label></div>";
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Hechos violatorios</h4>
                                    <div class="form-group" id="hechosviolatorios">
                                        <?php
                                        foreach ($calificacion as $hecho) {
                                            echo "<div class='checkbox'>";
                                            echo "<label><input type='checkbox' name ='hechos[]' checked='checked' value='" . $hecho->getIdHecho()->getId() . "'>";
                                            echo $hecho->getIdHecho()->getHecho() . "</label></div>";
                                        }
                                        ?>

                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Calificación</h4>
                                    <div id="resumen" class="padding-lg">
                                        <span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">
                    <a href="#" id="editarhechos">
                        <span class="badge bg-red"><i class="fa fa-edit"></i> Editar</span>
                    </a>
                    <a href="#" id="guardarhechos" style="display:none">
                        <span class="badge bg-blue"><i class="fa fa-save"></i> Guardar</span>
                    </a>
                </div>
            </div>
            <!------------- Finaliza formulario hechos y calificacion ----------------->
        </div>
    </div>
    <div class="row" id="denunciante">
        <div class="col-xs-12">
            <!---------------------- Inicia formulario de denunciante -------------------------->
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Denunciante
                        <small>
                            <?php
                            echo " / " . $persona->getNombres() . " " . $persona->getApellidos();
                            $fechanacString = $cola->getIdpersona()->getFechanacimiento();
                            $hoy = new DateTime('today');
                            if ($fechanacString == NULL) {
                                $edad = "";
                            } else {
                                $edad = $fechanacString->diff($hoy)->y;
                            }
                            echo " / " . $edad . " años";
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $anonimo = $form->get('checkbox')->setValue($persona->getAnonimo())->setAttributes(array(
                                    "id" => "anonimo",
                                    "name" => "solicitante_anonimo",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $anonimo->getOption('label') . $formLabel->closeTag();
                                echo "  " . $this->formInput($anonimo);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $numdoc = $form->get('numdoc')->setValue($persona->getNumeroDocumento())->setAttributes(array(
                                            "name" => "solicitante_numdoc",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($numdoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $tipodoc = $form->get('tipodoc')->setValue($persona->getTipoDocumento())->setAttributes(array(
                                            "name" => "solicitante_tipodoc",
                                            "disabled" => true
                                        ));
                                        ;
                                        echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($tipodoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $nombres = $form->get('nombre')->setValue($persona->getNombres())->setAttributes(array(
                                            "name" => "solicitante_nombre",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $nombres->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($nombres);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $apellidos = $form->get('apellido')->setValue($persona->getApellidos())->setAttributes(array(
                                            "name" => "solicitante_apellido",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $apellidos->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($apellidos);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        if (($cola->getIdpersona()->getFechanacimiento()) == NULL) {
                                            $value = $persona->getFechanacimiento();
                                        } else {
                                            $value = $persona->getFechanacimiento()->format("d/m/Y");
                                        }
                                        $fechanac = $form->get('fechanac')->setValue($value)->setAttributes(array(
                                            "name" => "solicitante_fechanac",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $fechanac->getOption('label') . " ";
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($fechanac);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $edad = $form->get('edad')->setValue($persona->getEdad())->setAttributes(array(
                                            "name" => "solicitante_edad",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $edad->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formNumber($edad);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $sexo = $form->get('sexo')->setValue($persona->getSexo())->setAttributes(array(
                                            "name" => "solicitante_sexo",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formRadio($sexo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $lgbti = $form->get('lgbti')->setValue($persona->getLgbti())->setAttributes(array(
                                            "name" => "solicitante_lgbti",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $lgbti->getOption('label') . $formLabel->closeTag() . "</br>";
                                        echo $this->formRadio($lgbti);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $correo = $form->get('correo')->setValue($persona->getCorreoElectronico())->setAttributes(array(
                                            "name" => "solicitante_correo",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $correo->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formEmail($correo);
                                        echo $this->formElementErrors($correo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $telefono = $form->get('telefono')->setValue($persona->getTelefono())->setAttributes(array(
                                            "name" => "solicitante_telefono",
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $telefono->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($telefono);
                                        echo $this->formElementErrors($telefono);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $direccionden = $form->get('direccion')->setValue($persona->getDireccion())->setAttributes(array(
                                            "name" => "solicitante_direccion",
                                            "required" => true,
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $direccionden->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($direccionden);
                                        echo $this->formElementErrors($direccionden);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $deptos = $this->deptos;
                                        $deptosOptions = array();
                                        foreach ($deptos as $deptoOption) {
                                            $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                        }
                                        $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($persona->getDepto()->getCodigo())->setAttributes(array(
                                            "name" => "solicitante_depto",
                                            "required" => true,
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($depto);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $munis = $this->munis;
                                        $munisOptions = array();
                                        foreach ($munis as $muniOption) {
                                            $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                        }
                                        $muni = $form->get('muni')->setValueOptions($munisOptions)->setValue($persona->getMuni()->getCodigo())->setAttributes(array(
                                            "name" => "solicitante_muni",
                                            "required" => true,
                                            "disabled" => true
                                        ));
                                        echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($muni);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $victimas = $this->victimas;
                                        foreach ($victimas as $victima) {
                                            if ($victima->getIdPersona()->getId() === $cola->getIdpersona()->getId()) {
                                                $denunciante_victima = 1;
                                                $denunciante_victima_attr = true;
                                            }
                                        }

                                        $victima = $form->get('victima')->setValue($denunciante_victima)->setAttributes(array(
                                            "name" => "solicitante_victima",
                                            "disabled" => $denunciante_victima_attr
                                        ));
                                        echo $formLabel->openTag() . $victima->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo "<label>¿El denunciante también es la víctima?</label>";
                                        echo "  " . $this->formRadio($victima);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">
                    <a href="#" data-toggle="" data-tt="tooltip" title="Editar" id="editarsolicitante">
                        <span class="badge bg-red"><i class="fa fa-edit"></i> Editar</span>
                    </a>
                    <a href="#" id="guardardenunciante" style="display:none">
                        <span class="badge bg-blue"><i class="fa fa-save"></i> Guardar</span>
                    </a>
                </div>
            </div>
            <!------------- Finaliza formulario denunciante ----------------->
        </div>
    </div>
    <div class="row">
        <!---------------- Inicia formulario victima --------------------->
        <div class="col-xs-12">
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-users"></i>
                    <h3 class="box-title">Víctimas
                        <small>

                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped" id="victimas">
                        <thead>
                            <tr>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Relación</th>
                                <th>Sexo</th>
                                <th>Edad</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $victimas = $this->victimas;
                            foreach ($victimas as $victima) {
                                echo "<tr>";
                                echo "<td>" . $victima->getIdPersona()->getNombres() . "</td>";
                                echo "<td>" . $victima->getIdPersona()->getApellidos() . "</td>";
                                echo "<td>" . $victima->getRelacionvictima()->getValor() . "</td>";
                                switch ($victima->getIdPersona()->getSexo()) {
                                    case 1:
                                        $sexo = "Masculino";
                                        break;
                                    case 2:
                                        $sexo = "Femenino";
                                    default:
                                        break;
                                }
                                echo "<td>" . $sexo . "</td>";
                                echo "<td>" . $victima->getIdPersona()->getEdad() . "</td>";
                                echo "<td><a href='" . $victima->getIdPersona()->getId() . "'><span class='badge bg-yellow'>Editar</span></a></td>";
                                echo "</tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <a href="<?php echo $this->url('recepcion', array('action' => 'registrovictima', 'id' => $expediente->getId())); ?>" data-toggle="modal" data-target="#newvictimaModal">
                        <span class="badge bg-green"><i class="glyphicon glyphicon-plus"></i> Nuevo</span>
                    </a>
                </div>
            </div>
        </div>
        <!-----------------Finaliza formulario victima ------------------->
    </div>
    <div class="row">
        <!---------------- Inicia formulario denunciados --------------------->
        <div class="col-xs-12">
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-users"></i>
                    <h3 class="box-title">Denunciados
                        <small>

                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped" id="denunciados">
                        <thead>
                            <tr>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Relación</th>
                                <th>Sexo</th>
                                <th>Edad</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $denunciados = $this->denunciados;
                            foreach ($denunciados as $denunciado) {
                                echo "<tr>";
                                echo "<td>" . $denunciado->getIdPersona()->getNombres() . "</td>";
                                echo "<td>" . $denunciado->getIdPersona()->getApellidos() . "</td>";
                                echo "<td>" . $denunciado->getRelacionagresor()->getValor() . "</td>";
                                switch ($denunciado->getIdPersona()->getSexo()) {
                                    case 1:
                                        $sexo = "Masculino";
                                        break;
                                    case 2:
                                        $sexo = "Femenino";
                                    default:
                                        break;
                                }
                                echo "<td>" . $sexo . "</td>";
                                echo "<td>" . $denunciado->getIdPersona()->getEdad() . "</td>";
                                echo "<td><a href='" . $denunciado->getIdPersona()->getId() . "'><span class='badge bg-yellow'>Editar</span></a></td>";
                                echo "</tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <a href="<?php echo $this->url('recepcion', array('action' => 'registrodenunciado', 'id' => $expediente->getId())); ?>" data-toggle="modal" data-target="#newdenunciadoModal">
                        <span class="badge bg-green"><i class="glyphicon glyphicon-plus"></i> Nuevo</span>
                    </a>
                </div>
            </div>
        </div>
        <!-----------------Finaliza formulario denunciados ------------------->
    </div>
    <div class="box-footer">
        <?php
        //echo $this->formElement($form->get('guardar'));
        echo $this->formElement($form->get('siguiente'));
        ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<div class="modal fade" tabindex="-1" role="dialog" id="newvictimaModal" >
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="newdenunciadoModal" >
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="messagesuccessmodal" >
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="alert alert-success">
                <strong>Los datos se han actualizado exitosamente.</strong>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="messageerrormodal" >
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="alert alert-danger">
                <strong>Ha ocurrido un error al actualizar los datos</strong>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#guardarhechos').click(function() {
            guardarhechos('<?php echo $this->url('recepcion', array('action' => 'editarexpediente', 'id' => $expediente->getId())); ?>', '<?php echo $this->url('recepcion', array('action' => 'investigacion', 'id' => $expediente->getId())) ?>');
        });
        $('#guardardenunciante').click(function() {
            guardardenunciante('<?php echo $this->url('recepcion', array('action' => 'editarexpediente', 'id' => $expediente->getId())); ?>', '<?php echo $this->url('recepcion', array('action' => 'investigacion', 'id' => $expediente->getId())) ?>');
        });
    });

    var url2 = '<?php echo $this->url('recepcion', array('action' => 'registrovictima', 'id' => $expediente->getId(), 'param1' => $persona->getId())); ?>';
    $('input[name="solicitante_victima"]').click(function() {
        if (($(this).val()) == 1) {
            $('#newvictimaModal').removeData('bs.modal');
            $('#newvictimaModal').modal({remote: url2});
            $('#newvictimaModal').modal('show');
            $('#victima_relacion').append("esto va aqui");
        }
    });
    $('#recepcion').submit(validateDerecho);
    $('#recepcion').submit(validateinstitucion);
</script>