<!---------------------- Inicia formulario de denunciado -------------------------->
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'method' => 'post',
    'id' => 'denunciado'
));
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Cerrar</span>
    </button>
    <h3 class="modal-title">
        <i class="fa fa-user"></i>
        <span>Denunciado</span>
    </h3>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $tipopersona = $form->get('tipodenunciado');
                echo $formLabel->openTag() . $tipopersona->getOption('label') . $formLabel->closeTag() . " ";
                echo $this->formMultiCheckbox($tipopersona);
                echo " - Haga clic en la casilla de verificación, si es persona no individual. (Representante legal, Grupo social, etc.)";
                ?>
            </div>
        </div>
    </div>
    <div class="row datos" id="individual">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $numdoc = $form->get('numdoc');
                echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($numdoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $tipodoc = $form->get('tipodoc');
                echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($tipodoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombre = $form->get('nombre')->setAttributes(array("required" => true));
                echo $formLabel->openTag() . $nombre->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombre);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $apellido = $form->get('apellido')->setAttributes(array("required" => true));
                echo $formLabel->openTag() . $apellido->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($apellido);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $sexo = $form->get('sexo');
                echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "</p>";
                echo $this->formRadio($sexo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $relacion = $form->get('relacion');
                echo $formLabel->openTag() . $relacion->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($relacion);
                ?>
            </div>
        </div>
    </div>
    <div class="row datos" id="noindividual" style="display: none">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombrenoin = $form->get('nombrenoin');
                echo $formLabel->openTag() . $nombrenoin->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombrenoin);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $contacto = $form->get('contacto');
                echo $formLabel->openTag() . $contacto->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($contacto);
                ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $direccion = $form->get('direccion');
                echo $formLabel->openTag() . $direccion->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($direccion);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $depto = $form->get('depto');
                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($depto);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $muni = $form->get('muni');
                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($muni);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $telefono = $form->get('telefono');
                echo $formLabel->openTag() . $telefono->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($telefono);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $correo = $form->get('correo');
                echo $formLabel->openTag() . $correo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($correo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $cargo = $form->get('cargo');
                echo $formLabel->openTag() . $cargo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($cargo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $institucion = $form->get('institucion');
                echo $formLabel->openTag() . $institucion->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($institucion);
                ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit"  id="guardardenunciado" class="btn btn-primary btn-flat" data-dismiss="modal"><i class="glyphicon glyphicon-floppy-disk"></i> Guardar</button>
</div>
<?php echo $this->form()->closeTag() ?>
<!------------- Finaliza formulario denunciado ----------------->
<script>
    $('#guardardenunciado').click(function() {
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url: '<?php echo $this->basePath() . "/validacion/guardardenunciado"; ?>',
            data: $('#denunciado').serialize(),
            success: function(data) {
                $('#denunciados').append("<tr>\n\
                        <td>" + data.numdoc + "</td>\n\
                        <td>" + data.nombres + " " + data.apellidos + "</td>\n\
                        <td>" + data.correo + "</td>\n\
                        <td>" + data.correo + "</td>\n\
                        <td><a href='' class='badge bg-yellow'>Editar</a></td>\n\
                        </tr>");
            },
            error: function() {
                alert('error');

            }
        });
    });
    $('#newdenunciadoModal').on('hidden.bs.modal', function() {
        $('form[name="denunciado"]')[0].reset();
        $('#noindividual').css("display", "none");
        $('#individual').css("display", "block");
    });
    $('input[name="tipodenunciado[]"]').click(function() {
        $('.datos').toggle();
    });
</script>