<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <?php
            switch ($this->page) {
                case "solicitante":
                    $class = "box box-warning";
                    break;
                case "visitante":
                    $class = "box box-info";
                    break;
            }
            ?>
            <div class="<?php echo $class ?>">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->subtitle; ?></h3>
                </div>
                <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttributes(array(
                    'action' => $this->url('recepcion', array('action' => 'guardar')),
                    'method' => 'post'
                ));
                // Get the form label plugin
                $formLabel = $this->plugin('formLabel');
                // Render the opening tag
                echo $this->form()->openTag($form);
                ?>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $fecha_actual = date("Y-m-d H:i:s");
                                //echo $fecha_actual;
                                $fecha = $form->get('fecha')->setValue($fecha_actual);
                                /* echo $formLabel->openTag() . $fecha->getOption('label') . " ";

                                  //echo $this->formElementErrors($name);
                                  echo $formLabel->closeTag(); */
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <!--<div class="col-xs-6">
                            <div class="form-group">

                          $hora_actual = date("H:i:s");
                          //echo $hora_actual;
                          $hora = $form->get('hora')->setValue($hora_actual);
                          echo $formLabel->openTag() . $hora->getOption('label') . " ";

                          //echo $this->formElementErrors($name);
                          echo $formLabel->closeTag();
                          echo $this->formInput($hora); */

                            </div>
                        </div>-->
                        <?php if ($this->url === 'solicitante') { ?>
                            <div class="col-xs-12">
                                <div class="form-group alert  alert-warning ">
                                    <?php
                                    $anonimo = $form->get('checkbox')->setAttributes(array('id' => 'anonimo', 'name' => 'anonimo'));
                                    echo $formLabel->openTag();
                                    echo $anonimo->getOption('label');
                                    echo $formLabel->closeTag();
                                    echo "  " . $this->formInput($anonimo);
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="col-xs-3">
                            <div class="form-group">
                                <?php
                                $tipodoc = $form->get('tipodoc');
                                echo $formLabel->openTag() . $tipodoc->getOption('label') . " ";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formSelect($tipodoc);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="form-group">
                                <?php
                                $numdoc = $form->get('numdoc');
                                echo $formLabel->openTag() . $numdoc->getOption('label') . " ";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($numdoc);

                                $id = $form->get('id')->setAttribute('id', 'id');
                                echo $this->formInput($id);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="form-group">
                                <?php
                                $fecha_nac = $form->get('nac');
                                echo $formLabel->openTag() . $fecha_nac->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha_nac);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="form-group">
                                <?php
                                $sexo = $form->get('sexo');
                                echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . " ";
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($sexo);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $nombre = $form->get('nombre');
                                        echo $formLabel->openTag() . $nombre->getOption('label') . " ";

                                        //echo $this->formElementErrors($name);
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($nombre);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $apellido = $form->get('apellido');
                                        echo $formLabel->openTag() . $apellido->getOption('label') . " ";

                                        //echo $this->formElementErrors($name);
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($apellido);
                                        ?>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-xs-6">
                            <?php
                            if ($this->url === 'visitante') {
                                $tipo = $form->get('tipopersona')->setValue('visitante');
                                echo $this->formInput($tipo);
                                ?>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $institucion = $form->get('institucion');
                                            echo $formLabel->openTag() . $institucion->getOption('label') . " ";

                                            //echo $this->formElementErrors($name);
                                            echo $formLabel->closeTag();
                                            echo $this->formInput($institucion);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $empleados = $this->empleados;
                                            $empleadosOptions = array();
                                            foreach ($empleados as $empleadoOption) {
                                                $empleadosOptions[$empleadoOption->getId()] = $empleadoOption->getNombres() . " " . $empleadoOption->getApellidos();
                                            }
                                            $empleado = $form->get('empleado')->setValueOptions($empleadosOptions);
                                            echo $formLabel->openTag() . $empleado->getOption('label') . " ";

                                            //echo $this->formElementErrors($name);
                                            echo $formLabel->closeTag();
                                            echo $this->formSelect($empleado);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            <?php } else { ?>
                                <div class="row">
                                    <?php
                                    $tipo = $form->get('tipopersona')->setValue('solicitante');
                                    echo $this->formInput($tipo);
                                    ?>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <?php
                                            $lgbti = $form->get('lgbti');
                                            echo "<p>" . $formLabel->openTag() . $lgbti->getOption('label');
                                            echo $formLabel->closeTag() . "</p>";
                                            echo $this->formRadio($lgbti);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="form-group">
                                            <?php
                                            $prioridad = $form->get('prioridad');
                                            echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                            echo $formLabel->closeTag() . "</p>";
                                            echo $this->formRadio($prioridad);
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="form-group">
                                            <?php
                                            $lapiceroverde = $form->get('lapiceroverde');
                                            echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                            echo $formLabel->closeTag() . "</p>";
                                            echo $this->formRadio($lapiceroverde);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                if ($this->url === 'visitante') {
                                    $motivo = $form->get('motivo');
                                    echo $formLabel->openTag() . $motivo->getOption('label') . " ";

                                    //echo $this->formElementErrors($name);
                                    echo $formLabel->closeTag();
                                    echo $this->formTextarea($motivo);
                                } else {
                                    $obs = $form->get('obs');
                                    echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                    //echo $this->formElementErrors($name);
                                    echo $formLabel->closeTag();
                                    echo $this->formTextarea($obs);
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <?php echo $this->formElement($form->get('guardar')) ?>
                    <?php echo $this->formElement($form->get('cancelar')) ?>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</section>


<script type="text/javascript">
    $(document).ready(function() {
        $('#numdoc').on('keypress', function(e) {
            if (e.which == 32)
                return false;
        });
        $("#numdoc").autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: "<?php echo $this->basePath(); ?>/validacion/validardpi",
                    dataType: "json",
                    type: "POST",
                    data: {
                        term: request.term
                    },
                    success: function(data) {
                        response($.map(data, function(item) {
                            return {
                                label: item,
                                value: item
                            };
                        }));
                    }
                    /*error: function(a, b, c) {
                     debugger;
                     }*/
                });

            }
        });
        $("#numdoc").focusout(function() {
            $.ajax({
                url: "<?php echo $this->basePath(); ?>/validacion/seleccionardpi",
                dataType: "json",
                type: "POST",
                data: {
                    term: $("#numdoc").val()
                },
                success: function(data) {
                    if (!$("#numdoc").val()) {

                    } else {
                        $('#id').val(data[0]);
                        $('#tipodoc').val(data[1]);
                        $('#datepicker').val(data[2]);
                        //$('#sexo').val(data[3]);
                        $('#nombres').val(data[4]);
                        $('#apellidos').val(data[5]);
                        var $radios = $('input:radio[name=sexo]');
                        if ($radios.is(':checked') === false) {
                            $radios.filter('[value=' + data[3] + ']').prop('checked', true);
                        }
                    }
                },
                error: function() {
                    $('#id').val();
                    $('#tipodoc').val();
                    $('#datepicker').val();
                    //$('#sexo').val(data[3]);
                    $('#nombres').val();
                    $('#apellidos').val();
                }
            });
            if ($("#numdoc").val() !== '') {
                $("#tipodoc").attr("required", "true");
            }
        });
        $("#anonimo").change(function() {
            if (this.checked) {
                $("#tipodoc").attr('readonly', true);
                $("#numdoc").attr('readonly', true);
                $("#nombres").val('Anónimo', true);
                $("#apellidos").val('Anónimo', true);
                $("#datepicker").attr('readonly', true);
            } else {
                $('#recepcion').trigger("reset");
                $("#tipodoc").attr('readonly', false);
                $("#numdoc").attr('readonly', false);
                $("#datepicker").attr('readonly', false);
            }
        });
        /*$("#anonimo").change(function() {

         });*/
    });

</script>


