<!---------------------- Inicia formulario de victima -------------------------->
<?php
$denunciante = $this->denunciante;
$expediente = $this->expediente;
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url('recepcion', array('action' => 'guardarvictima')),
    'method' => 'post',
    'data-toggle' => 'validator',
    'id' => 'victima',
    'role' => 'form'
));

$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);

$param = $form->get('param')->setValue($this->param);
echo $this->formInput($param);

if (!empty($denunciante)) {
    $victima_idpersona = $form->get('id')->setValue($denunciante->getId())->setAttributes(array(
        "name" => "idpersona",
        "id" => "idpersona"
    ));
    echo $this->formInput($victima_idpersona);
    $victima_numdoc = $denunciante->getNumeroDocumento();
    $victima_tipodoc = $denunciante->getTipoDocumento();
    $victima_nombres = $denunciante->getNombres();
    $victima_apellidos = $denunciante->getApellidos();
    if ($denunciante->getFechanacimiento() == null) {
        $victima_fechanac = $denunciante->getFechanacimiento();
    } else {
        $victima_fechanac = $denunciante->getFechanacimiento()->format("d/m/Y");
    }
    $victima_edad = $denunciante->getEdad();
    $victima_sexo = $denunciante->getSexo();
    $victima_lgbti = $denunciante->getLgbti();
    $victima_direccion = $denunciante->getDireccion();
    $victima_departamento = $denunciante->getDepto()->getCodigo();
    $victima_municipio = $denunciante->getMuni()->getCodigo();
    $victima_telefono = $denunciante->getTelefono();
    $victima_correo = $denunciante->getCorreoElectronico();
    $victima_relacion = 5;
} else {
    $victima_idpersona = $form->get('id')->setAttributes(array(
        "name" => "idpersona",
        "id" => "idpersona"
    ));
    echo $this->formInput($victima_idpersona);
    $victima_numdoc = NULL;
    $victima_tipodoc = NULL;
    $victima_nombres = NULL;
    $victima_apellidos = NULL;
    $victima_fechanac = NULL;
    $victima_edad = NULL;
    $victima_sexo = NULL;
    $victima_lgbti = NULL;
    $victima_direccion = NULL;
    $victima_departamento = NULL;
    $victima_municipio = NULL;
    $victima_telefono = NULL;
    $victima_correo = NULL;
    $victima_relacion = NULL;
}
$id = $form->get('id')->setValue($expediente)->setAttributes(array(
    "name" => "idexpediente",
    "id" => "idexpediente"
        ));
echo $this->formInput($id);
?>
<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Cerrar</span>
    </button>
    <h3 class="modal-title">
        <i class="fa fa-user"></i>
        <span>Víctima</span>
    </h3>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $tipopersona = $form->get('tipovictima')->setAttributes(array(
                    "name" => "victima_tipo",
                    "id" => "victima_tipo"
                ));
                echo $formLabel->openTag() . $tipopersona->getOption('label') . $formLabel->closeTag() . " ";
                echo $this->formCheckbox($tipopersona);
                echo " - Haga clic en la casilla de verificación, si es persona no individual. (Representante legal, Grupo social, etc.)";
                ?>
            </div>
        </div>
    </div>
    <div class="row" id="individual">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $numdoc = $form->get('numdoc')->setValue($victima_numdoc)->setAttributes(array(
                    "name" => "victima_numdoc",
                    "id" => "victima_numdoc"
                ));
                echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($numdoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $tipodoc = $form->get('tipodoc')->setValue($victima_tipodoc)->setAttributes(array(
                    "name" => "victima_tipodoc",
                    "id" => "victima_tipodoc"
                ));
                echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($tipodoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombre = $form->get('nombres')->setValue($victima_nombres)->setAttributes(array(
                    "name" => "victima_nombres",
                    "id" => "victima_nombres",
                    "required" => true
                ));
                echo $formLabel->openTag() . $nombre->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombre);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $apellido = $form->get('apellidos')->setValue($victima_apellidos)->setAttributes(array(
                    "name" => "victima_apellidos",
                    "id" => "victima_apellidos",
                    "required" => true
                ));
                echo $formLabel->openTag() . $apellido->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($apellido);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $fechanac = $form->get('fechanac')->setValue($victima_fechanac)->setAttributes(array(
                    "name" => "victima_fechanac",
                    "id" => "victima_fechanac"
                ));
                echo $formLabel->openTag() . $fechanac->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($fechanac);
                ?>
            </div>
        </div>
        <div class="col-xs-3">
            <div class="form-group">
                <?php
                $edad = $form->get('edad')->setValue($victima_edad)->setAttributes(array(
                    "name" => "victima_edad",
                    "id" => "victima_edad",
                    "required" => true
                ));
                echo $formLabel->openTag() . $edad->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($edad);
                ?>
            </div>
        </div>
        <div class="col-xs-3">
            <div class="form-group">
                <?php
                $sexo = $form->get('sexo')->setValue($victima_sexo)->setAttributes(array(
                    "name" => "victima_sexo",
                    "id" => "victima_sexo",
                    "required" => true
                ));
                echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "</p>";
                echo $this->formRadio($sexo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $lgbti = $form->get('lgbti')->setValue($victima_lgbti)->setAttributes(array(
                    "name" => "victima_lgbti",
                    "id" => "victima_lgbti"
                ));
                echo "<p>" . $formLabel->openTag() . $lgbti->getOption('label') . $formLabel->closeTag() . "</p>";
                echo $this->formRadio($lgbti);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombreusual = $form->get('nombreusual')->setAttributes(array(
                    "name" => "victima_nombreusual",
                    "id" => "victima_nombreusual"
                ));
                echo $formLabel->openTag() . $nombreusual->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombreusual);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $relaciondtevic = $this->relaciondtevic;
                $relacionOptions = array();
                foreach ($relaciondtevic as $relacionOption) {
                    $relacionOptions[$relacionOption->getId()] = $relacionOption->getValor();
                }
                $relacion = $form->get('relacion')->setValueOptions($relacionOptions)->setValue($victima_relacion)->setAttributes(array(
                    "name" => "victima_relacion",
                    "id" => "victima_relacion",
                    "required" => true,
                ));
                echo $formLabel->openTag() . $relacion->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($relacion);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $comunidadlinguistica = $this->comunidadlinguistica;
                $comunidadOptions = array();
                foreach ($comunidadlinguistica as $comunidadOption) {
                    $comunidadOptions[$comunidadOption->getId()] = $comunidadOption->getValor();
                }
                $comunidad = $form->get('comunidad')->setValueOptions($comunidadOptions)->setAttributes(array(
                    "name" => "victima_comunidad",
                    "id" => "victima_comunidad",
                    "required" => true
                ));
                echo $formLabel->openTag() . $comunidad->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($comunidad);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $pueblopertenencia = $this->pueblopertenencia;
                $puebloOptions = array();
                foreach ($pueblopertenencia as $puebloOption) {
                    $puebloOptions[$puebloOption->getId()] = $puebloOption->getValor();
                }
                $pertenencia = $form->get('pertenencia')->setValueOptions($puebloOptions)->setAttributes(array(
                    "name" => "victima_pertenencia",
                    "id" => "victima_pertenencia",
                    "required" => true
                ));
                echo $formLabel->openTag() . $pertenencia->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($pertenencia);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nacionalidad = $this->nacionalidad;
                $nacionalidadOptions = array();
                foreach ($nacionalidad as $nacionalidadOption) {
                    $nacionalidadOptions[$nacionalidadOption->getId()] = $nacionalidadOption->getValor();
                }
                $nac = $form->get('nacionalidad')->setValueOptions($nacionalidadOptions)->setAttributes(array(
                    "name" => "victima_nacionalidad",
                    "id" => "victima_nacionalidad",
                    "required" => true
                ));
                echo $formLabel->openTag() . $nac->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($nac);
                ?>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="form-group">
                <p>
                    <label>Grupo Vulnerable</label>
                </p>
                <?php
                $grupovulnerable = $this->grupovulnerable;
                $grupoOptions = array();
                foreach ($grupovulnerable as $grupoOption) {
                    $grupo = $form->get('grupovulnerable')->setLabel($grupoOption->getValor())->setAttributes(array(
                        "required" => true
                    ));
                    echo "<div class='checkbox col-xs-6'>";
                    echo "<label><input type='checkbox' name='victima_grupovulnerable[]' value='" . $grupoOption->getId() . "'>" . $grupoOption->getValor() . "</label>";
                    echo "</div>";
                }
                ?>
            </div>
        </div>
    </div>
    <div class="row" id="noindividual" style="display: none">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombrecolectivo = $form->get('nombrecolectivo')->setAttributes(array(
                    "name" => "victima_nombrecolectivo",
                    "id" => "victima_nombrecolectivo",
                    "disabled" => true
                ));
                echo $formLabel->openTag() . $nombrecolectivo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombrecolectivo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $contacto = $form->get('contacto')->setAttributes(array(
                    "name" => "victima_contacto",
                    "id" => "victima_contacto",
                    "disabled" => true
                ));
                echo $formLabel->openTag() . $contacto->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($contacto);
                ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $direccion = $form->get('direccion')->setValue($victima_direccion)->setAttributes(array(
                    "name" => "victima_direccion",
                    "id" => "victima_direccion"
                ));
                echo $formLabel->openTag() . $direccion->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($direccion);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $deptos = $this->deptos;
                $deptosOptions = array();
                foreach ($deptos as $deptoOption) {
                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                }
                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($victima_departamento)->setAttributes(array(
                    "name" => "victima_depto",
                    "id" => "victima_depto",
                    "required" => true
                ));
                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($depto);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $munis = $this->munis;
                $munisOptions = array();
                foreach ($munis as $muniOption) {
                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                }
                $muni = $form->get('muni')->setValueOptions($munisOptions)->setValue($victima_municipio)->setAttributes(array(
                    "name" => "victima_muni",
                    "id" => "victima_muni",
                    "required" => true
                ));
                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($muni);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $telefono = $form->get('telefono')->setValue($victima_telefono)->setAttributes(array(
                    "name" => "victima_telefono",
                    "id" => "victima_telefono"
                ));
                echo $formLabel->openTag() . $telefono->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($telefono);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $correo = $form->get('correo')->setValue($victima_correo)->setAttributes(array(
                    "name" => "victima_correo",
                    "id" => "victima_correo"
                ));
                echo $formLabel->openTag() . $correo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($correo);
                ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit"  id="guardarvictima" class="btn btn-primary btn-flat" ><i class="glyphicon glyphicon-floppy-disk"></i> Guardar</button>
</div>
<?php echo $this->form()->closeTag() ?>
<!------------- Finaliza formulario victima ----------------->
<script>
    $(document).ready(function() {
        $("#victima_fechanac").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            onSelect: function(dateString) {
                var dateString = $('#victima_fechanac').val().split("/");
                var dateObject = new Date(dateString[2], dateString[1] - 1, dateString[0]);
                var today = new Date();
                var age = Math.floor((today - dateObject) / (365.25 * 24 * 60 * 60 * 1000));
                $('#victima_edad').val(age);

            }
        });
        if (($("#victima_relacion option:selected").val()) == 5) {
            $("#victima_relacion").attr("readonly", true);
        }
    });
    // Validacion de formulario de victima
    $('#victima').validator();

    // Llamado a funcion validar dpi para ver si existe en la db
    $("#victima_tipodoc").change(function() {
        $("#victima_numdoc").attr("required", "true");
    });
    // Llamado a funcion obtener datos segun el dpi
    $("#victima_numdoc").autocomplete({
        source: function(request, response) {
            $.ajax({
                url: "<?php echo $this->basePath(); ?>/validacion/validardpi",
                dataType: "json",
                type: "POST",
                data: {
                    term: request.term
                },
                success: function(data) {
                    response($.map(data, function(item) {
                        return {
                            label: item,
                            value: item
                        };
                    }));
                }
            });
        },
        minLength: 6
    });

    // Llamado a funcion completar datos para llenar formulario
    $("#victima_numdoc").focusout(function() {
        $.ajax({
            url: "<?php echo $this->basePath(); ?>/validacion/seleccionardpi",
            dataType: "json",
            type: "POST",
            data: {
                term: $("#victima_numdoc").val()
            },
            success: function(data) {
                if ($("#victima_numdoc").val()) {
                    $('#idpersona').val(data[0]);
                    $('#victima_tipodoc').val(data[1]);
                    $('#victima_fechanac').val(data[2]);
                    $('#victima_nombres').val(data[4]);
                    $('#victima_apellidos').val(data[5]);
                    var radios = $("input[name='victima_sexo']");
                    if (radios.is(':checked') === false) {
                        radios.filter('[value=' + data[3] + ']').prop('checked', true);
                    }
                    var lgbti = $("input[name='victima_lgbti']");
                    if (lgbti.is(':checked') === false) {
                        lgbti.filter('[value=' + data[6] + ']').prop('checked', true);
                    }
                    $('#victima_correo').val(data[7]);
                    $('#victima_telefono').val(data[8]);
                    $('#victima_direccion').val(data[9]);
                    $('#victima_depto').val(data[10]);
                    $('#victima_muni').val(data[11]);
                }
            }
        });
        if ($("#victima_numdoc").val() !== '') {
            $("#victima_tipodoc").attr("required", "true");
        }

    });

    // Borra los datos del modal victima
    $('#newvictimaModal').on('hidden.bs.modal', function() {
        $('#newvictimaModal').removeData('bs.modal');
        $('form[name="victima"]')[ 0].reset();
        $('#individual').show();
        $("#individual :input").attr("disabled", false);
    });

    // Lista municipios de cada departamento
    $("select[name='victima_depto']").change(function() {
        var depto = $(this).val();
        $.ajax({
            url: "<?php echo $this->basePath(); ?>/validacion/listarmunicipios",
            dataType: 'json',
            type: 'POST',
            data: {depto: depto},
            success: function(data) {
                $("select[name='victima_muni']").append($("<option>Seleccione una opción</option>"));
                $.each(data, function(key, value) {
                    $("select[name='victima_muni']")
                            .append($("<option></option>")
                                    .attr("value", key)
                                    .text(value));
                });
            }
        });
        $("select[name='victima_muni']").empty().prop("selectedIndex", -1);
    });

    //Victima tipo
    var individual = $('#individual');
    var noindividual = $('#noindividual');
    $("input[name='victima_tipo']").click(function() {
        if ($(this).is(":checked")) {
            individual.find(':input').attr({disabled: true, required: false});
            $("#individual").css("display", "none");
            noindividual.find(':input').attr({disabled: false});
            $("#noindividual").css("display", "block");
        } else {
            individual.find(':input').attr({disabled: false, required: true});
            $("#noindividual").css("display", "none");
            noindividual.find(':input').attr({disabled: true});
            $("#individual").css("display", "block");
        }
    });
</script>