<!---------------------- Inicia formulario de denunciado -------------------------->
<?php
$expediente = $this->expediente;
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url('recepcion', array('action' => 'guardardenunciado')),
    'method' => 'post',
    'data-toggle' => 'validator',
    'id' => 'denunciado',
    'role' => 'form'
));
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);

$param = $form->get('param')->setValue($this->param);
echo $this->formInput($param);

$id = $form->get('id')->setValue($expediente)->setAttributes(array(
    "name" => "idexpediente"
        ));
echo $this->formInput($id);

$denunciado_idpersona = $form->get('id')->setValue("")->setAttributes(array(
    "name" => "idpersona",
    "id" => "idpersona"
        ));
echo $this->formInput($denunciado_idpersona);
?>
<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Cerrar</span>
    </button>
    <h3 class="modal-title">
        <i class="fa fa-user"></i>
        <span>Denunciado</span>
    </h3>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $tipopersona = $form->get('tipodenunciado')->setAttributes(array(
                    "name" => "denunciado_tipo",
                    "id" => "denunciado_tipo"
                ));
                echo $formLabel->openTag() . $tipopersona->getOption('label') . $formLabel->closeTag() . " ";
                echo $this->formCheckbox($tipopersona);
                echo " - Haga clic en la casilla de verificación, si es persona no individual. (Representante legal, Grupo social, etc.)";
                ?>
            </div>
        </div>
    </div>
    <div class="row" id="individual">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $numdoc = $form->get('numdoc')->setAttributes(array(
                    "name" => "denunciado_numdoc",
                    "id" => "denunciado_numdoc"
                ));
                echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($numdoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $tipodoc = $form->get('tipodoc')->setAttributes(array(
                    "name" => "denunciado_tipodoc",
                    "id" => "denunciado_tipodoc"
                ));
                echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($tipodoc);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombre = $form->get('nombres')->setAttributes(array(
                    "name" => "denunciado_nombres",
                    "id" => "denunciado_nombres",
                    "required" => true
                ));
                echo $formLabel->openTag() . $nombre->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombre);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $apellido = $form->get('apellidos')->setAttributes(array(
                    "name" => "denunciado_apellidos",
                    "id" => "denunciado_apellidos",
                    "required" => true
                ));
                echo $formLabel->openTag() . $apellido->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($apellido);
                ?>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $sexo = $form->get('sexo')->setAttributes(array(
                    "name" => "denunciado_sexo",
                    "id" => "denunciado_sexo",
                    "required" => true
                ));
                echo "<p>" . $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "</p>";
                echo $this->formRadio($sexo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $relacionvicagr = $this->relacionvicagr;
                $relacionOptions = array();
                foreach ($relacionvicagr as $relacionOption) {
                    $relacionOptions[$relacionOption->getId()] = $relacionOption->getValor();
                }
                $relacion = $form->get('relacion')->setValueOptions($relacionOptions)->setAttributes(array(
                    "name" => "denunciado_relacion",
                    "id" => "denunciado_relacion",
                    "required" => true
                ));
                echo $formLabel->openTag() . $relacion->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($relacion);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $comunidadlinguistica = $this->comunidadlinguistica;
                $comunidadOptions = array();
                foreach ($comunidadlinguistica as $comunidadOption) {
                    $comunidadOptions[$comunidadOption->getId()] = $comunidadOption->getValor();
                }
                $comunidad = $form->get('comunidad')->setValueOptions($comunidadOptions)->setAttributes(array(
                    "name" => "denunciado_comunidad",
                    "id" => "denunciado_comunidad",
                    "required" => true
                ));
                echo $formLabel->openTag() . $comunidad->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($comunidad);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $pueblopertenencia = $this->pueblopertenencia;
                $puebloOptions = array();
                foreach ($pueblopertenencia as $puebloOption) {
                    $puebloOptions[$puebloOption->getId()] = $puebloOption->getValor();
                }
                $pertenencia = $form->get('pertenencia')->setValueOptions($puebloOptions)->setAttributes(array(
                    "name" => "denunciado_pertenencia",
                    "id" => "denunciado_pertenencia",
                    "required" => true
                ));
                echo $formLabel->openTag() . $pertenencia->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($pertenencia);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nacionalidad = $this->nacionalidad;
                $nacionalidadOptions = array();
                foreach ($nacionalidad as $nacionalidadOption) {
                    $nacionalidadOptions[$nacionalidadOption->getId()] = $nacionalidadOption->getValor();
                }
                $nac = $form->get('nacionalidad')->setValueOptions($nacionalidadOptions)->setAttributes(array(
                    "name" => "denunciado_nacionalidad",
                    "id" => "denunciado_nacionalidad",
                    "required" => true
                ));
                echo $formLabel->openTag() . $nac->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($nac);
                ?>
            </div>
        </div>
    </div>
    <div class="row" id="noindividual" style="display: none">
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $nombrecolectivo = $form->get('nombrecolectivo')->setAttributes(array(
                    "name" => "denunciado_nombrecolectivo",
                    "id" => "denunciado_nombrecolectivo",
                    "disabled" => true
                ));
                echo $formLabel->openTag() . $nombrecolectivo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($nombrecolectivo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $contacto = $form->get('contacto')->setAttributes(array(
                    "name" => "denunciado_contacto",
                    "id" => "denunciado_contacto",
                    "disabled" => true
                ));
                echo $formLabel->openTag() . $contacto->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($contacto);
                ?>
            </div>
        </div>
    </div>
    <div class="row" id="contacto">
        <div class="col-xs-12">
            <div class="form-group">
                <?php
                $direccion = $form->get('direccion')->setAttributes(array(
                    "name" => "denunciado_direccion",
                    "id" => "denunciado_direccion",
                    "required" => true
                ));
                echo $formLabel->openTag() . $direccion->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($direccion);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $deptos = $this->deptos;
                $deptosOptions = array();
                foreach ($deptos as $deptoOption) {
                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                }
                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setAttributes(array(
                    "name" => "denunciado_depto",
                    "id" => "denunciado_depto",
                    "required" => true
                ));
                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($depto);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $munis = $this->munis;
                $munisOptions = array();
                foreach ($munis as $muniOption) {
                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                }
                $muni = $form->get('muni')->setValueOptions($munisOptions)->setAttributes(array(
                    "name" => "denunciado_muni",
                    "id" => "denunciado_muni",
                    "required" => true
                ));
                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                echo $this->formSelect($muni);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $telefono = $form->get('telefono')->setAttributes(array(
                    "name" => "denunciado_telefono",
                    "id" => "denunciado_telefono"
                ));
                echo $formLabel->openTag() . $telefono->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($telefono);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $correo = $form->get('correo')->setAttributes(array(
                    "name" => "denunciado_correo",
                    "id" => "denunciado_correo"
                ));
                echo $formLabel->openTag() . $correo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($correo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $cargo = $form->get('cargo')->setAttributes(array(
                    "name" => "denunciado_cargo",
                    "id" => "denunciado_cargo"
                ));
                echo $formLabel->openTag() . $cargo->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($cargo);
                ?>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="form-group">
                <?php
                $institucion = $form->get('institucion')->setAttributes(array(
                    "name" => "denunciado_institucion",
                    "id" => "denunciado_institucion"
                ));
                echo $formLabel->openTag() . $institucion->getOption('label') . $formLabel->closeTag();
                echo $this->formInput($institucion);
                ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit"  id="guardardenunciado" class="btn btn-primary btn-flat"><i class="glyphicon glyphicon-floppy-disk"></i> Guardar</button>
</div>
<?php echo $this->form()->closeTag() ?>
<!------------- Finaliza formulario denunciado ----------------->
<script>
    $(document).ready(function() {
        $("#denunciado_fechanac").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            onSelect: function(dateString) {
                var dateString = $('#denunciado_fechanac').val().split("/");
                var dateObject = new Date(dateString[2], dateString[1] - 1, dateString[0]);
                var today = new Date();
                var age = Math.floor((today - dateObject) / (365.25 * 24 * 60 * 60 * 1000));
                $('#denunciado_edad').val(age);

            }
        });
        /*$("#noindividual").hide();
         $("#noindividual :input").attr("disabled", true);
         if (($("#denunciado_relacion option:selected").val()) == 5) {
         $("#denunciado_relacion").attr("readonly", true);
         }*/
    });
    $('#denunciado').validator();
    /*
     *  Llamado a funcion validar dpi para ver si existe en la db
     */
    $("#denunciado_tipodoc").change(function() {
        $("#denunciado_numdoc").attr("required", "true");
    });

    /*
     *  Llamado a funcion obtener datos segun el dpi
     */

    $("#denunciado_numdoc").autocomplete({
        source: function(request, response) {
            $.ajax({
                url: "<?php echo $this->basePath(); ?>/validacion/validardpi",
                dataType: "json",
                type: "POST",
                data: {
                    term: request.term
                },
                success: function(data) {
                    response($.map(data, function(item) {
                        return {
                            label: item,
                            value: item
                        };
                    }));
                }
            });
        },
        minLength: 6
    });
    /*
     *  Llamado a funcion completar datos para llenar formulario
     */
    $("#denunciado_numdoc").focusout(function() {
        $.ajax({
            url: "<?php echo $this->basePath(); ?>/validacion/seleccionardpi",
            dataType: "json",
            type: "POST",
            data: {
                term: $("#denunciado_numdoc").val()
            },
            success: function(data) {
                if ($("#denunciado_numdoc").val()) {
                    $('#idpersona').val(data[0]);
                    $('#denunciado_tipodoc').val(data[1]);
                    $('#denunciado_fechanac').val(data[2]);
                    $('#denunciado_nombres').val(data[4]);
                    $('#denunciado_apellidos').val(data[5]);
                    var radios = $("input[name='denunciado_sexo']");
                    if (radios.is(':checked') === false) {
                        radios.filter('[value=' + data[3] + ']').prop('checked', true);
                    }
                    var lgbti = $("input[name='denunciado_lgbti']");
                    if (lgbti.is(':checked') === false) {
                        lgbti.filter('[value=' + data[6] + ']').prop('checked', true);
                    }
                    $('#denunciado_correo').val(data[7]);
                    $('#denunciado_telefono').val(data[8]);
                    $('#denunciado_direccion').val(data[9]);
                    $('#denunciado_depto').val(data[10]);
                    $('#denunciado_muni').val(data[11]);
                }
            },
        });
        if ($("#denunciado_numdoc").val() !== '') {
            $("#denunciado_tipodoc").attr("required", "true");
        }

    });
    $('#newdenunciadoModal').on('hidden.bs.modal', function() {
        $('#newdenunciadoModal').removeData('bs.modal');
        $('form[name="denunciado"]')[ 0].reset();
        /*$('#noindividual').hide();
         $("#noindividual :input").attr("disabled", true);*/
        $('#individual').show();
        $("#individual :input").attr("disabled", false);
    });
    $("select[name='denunciado_depto']").change(function() {
        var depto = $(this).val();
        $.ajax({
            url: "<?php echo $this->basePath(); ?>/validacion/listarmunicipios",
            dataType: 'json',
            type: 'POST',
            data: {depto: depto},
            success: function(data) {
                $("select[name='denunciado_muni']").append($("<option>Seleccione una opción</option>"));
                $.each(data, function(key, value) {
                    $("select[name='denunciado_muni']")
                            .append($("<option></option>")
                                    .attr("value", key)
                                    .text(value));
                });
            }
        });
        $("select[name='denunciado_muni']").empty().prop("selectedIndex", -1);
    });

    //Denunciado tipo
    var individual = $('#individual');
    var noindividual = $('#noindividual');
    $("input[name='denunciado_tipo']").click(function() {
        if ($(this).is(":checked")) {
            individual.find(':input').attr({disabled: true, required: false});
            $("#individual").css("display", "none");
            noindividual.find(':input').attr({disabled: false});
            $("#noindividual").css("display", "block");
        } else {
            individual.find(':input').attr({disabled: false, required: true});
            $("#noindividual").css("display", "none");
            noindividual.find(':input').attr({disabled: true});
            $("#individual").css("display", "block");
        }
    });
</script>