<section class="content-header">
    <h1><?php echo $this->title; ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $this->subtitle; ?></h3>
                </div>
                <div class="box-body">
                    <table id="datatable" class="table table-bordered table-hover dataTable" cellspacing="0">

                        <thead>
                            <tr>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Detalle</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $personas = $this->personas;
                            foreach ($personas as $persona):
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $persona->getNombres(); ?>
                                    </td>
                                    <td>
                                        <?php echo $persona->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('recepcion/procesar', array('action' => 'detallebuscar', 'id' => $persona->getId())); ?>" data-tt="tooltip" title="Detalles">
                                            <span class="glyphicon glyphicon-search fa-lg"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/solicitante" tooltip="Solicitante">
        </a>
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/visitante" tooltip="Visitante">
        </a>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>





