<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Búsqueda de personas</h3>
                </div>
                <div class="box-body">
                    <table id="datatable" class="table table-bordered table-hover dataTable" cellspacing="0">

                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Hora</th>
                                <th>Tipo</th>
                                <th>Nombre</th>
                                <th>Motivo / Observaciones</th>
                                <th>Detalle</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $visitas = $this->visitas;
                            foreach ($visitas as $visita):
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $visita->getFechaentrada()->format("d/m/Y"); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getFechaentrada()->format("H:i:s"); ?>
                                    </td>
                                    <td>
                                        <span>Visita</span>
                                    </td>
                                    <td>
                                        <?php echo $visita->getIdpersona()->getNombres() . " " . $visita->getIdpersona()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getMotivovisita(); ?>
                                    </td>
                                    <td class="details-control">
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'detallevisita', 'id' => $visita->getId())); ?>" data-toggle="modal" data-target="#detailsModal" data-tt="tooltip" title="Detalles">
                                            <span class="glyphicon glyphicon-search fa-lg"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <?php
                            $solicitudes = $this->solicitudes;
                            foreach ($solicitudes as $solicitud):
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $solicitud->getFechaentrada()->format("d/m/Y"); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getFechaentrada()->format("H:i:s"); ?>
                                    </td>
                                    <td>
                                        <span>Solicitud</span>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getIdpersona()->getNombres() . " " . $solicitud->getIdpersona()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $solicitud->getObservaciones(); ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'detallecola', 'id' => $solicitud->getId())); ?>" data-toggle="modal" data-target="#detailsModal" data-tt="tooltip" title="Detalles">
                                            <span class="glyphicon glyphicon-search fa-lg"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="fixed-action-btn">
    <nav class="fab">
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/solicitante" tooltip="Solicitante">
        </a>
        <a class="fab-button bg-primary" href="<?php $this->url('recepcion'); ?>./registro/visitante" tooltip="Visitante">
        </a>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<!--<script src="//cdn.datatables.net/plug-ins/1.10.15/sorting/date-euro.js"></script>-->

<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({
            "columnDefs": [
                {"width": "5%", "targets": 5}
            ],
            "bSort": true,
            "order": [[0, "desc"]]

        });
    });
</script>



