<?php
$expediente = $this->expediente["datos"];
$persona = $this->expediente["persona"];
$calificacion = $this->expediente["calificacion"];
$cola = $expediente->getIdCola();
?>
<section class="content-header">
    <h1>Orientacion # <?php /* echo $expediente->getNumero(); */ ?></h1>
    <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Solicitud) Etapa 1 de 3</span>
        </div>
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Orientación) Etapa 2 de 3</span>
        </div>
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 34%">
            <span>(Resumen) Etapa 3 de 3</span>
        </div>
    </div>
</section>
<section class="content">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url('recepcion', array('action' => 'guardarorientacion')),
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    $formLabel = $this->plugin('formLabel');

    //$pid = $form->get('pid')->setValue($cola->getIdpersona()->getId());
    $id = $form->get('id')->setValue($this->id);
    //echo $this->formInput($pid);
    echo $this->formInput($id);
    ?>
    <div class="row">
        <div class = "col-xs-6">
            <div class = "box box-default color-palette-box collapsed-box">
                <div class = "box-header with-border">
                    <i class = "fa fa-file"></i>
                    <h3 class = "box-title">Solicitud</h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <span class="description">
                        <?php
                        echo $cola->getFechaentrada()->format("d/m/Y H:i:s");
                        switch ($cola->getPrioridad()) {
                            case '1':
                                $class = "red-text";
                                $prioridad = "Urgente";
                                break;
                            case '2':
                                $class = "yellow-text";
                                $prioridad = "Importante";
                                break;
                            case '3':
                                $class = "green-text";
                                $prioridad = "Normal";
                        }
                        echo " - " . $prioridad;
                        ?>
                    </span>
                </div>
                <div class = "box-body">
                    <div class = "row">
                        <div class = "col-xs-12">
                            <div class="form-group">
                                <?php
                                $fechasol = $form->get('fecha')->setValue($cola->getFechaentrada()->format("d/m/Y H:i:s"))->setAttributes(array("name" => "fechasol", "type" => "date", "class" => "form-control datepicker", "disabled" => true));
                                echo $formLabel->openTag() . $fechasol->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechasol);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $prioridad = $form->get('prioridad')->setValue($cola->getPrioridad());
                                echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($prioridad);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $lapiceroverde = $form->get('lapiceroverde')->setValue($cola->getLapiceroverde());
                                echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($lapiceroverde);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $obs = $form->get('obs')->setValue($cola->getObservaciones());
                                echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($obs);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Solicitante</h3>
                    <div class="pull-right">
                        <a href="#" data-toggle="" data-tt="tooltip" title="Editar" id="editarsolicitante">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <span class="description">
                        <?php
                        echo $persona->getNombres() . " " . $persona->getApellidos();
                        $fechanacString = $persona->getFechanacimiento();
                        $hoy = new DateTime('today');
                        if ($fechanacString == NULL) {
                            $edad = "";
                        } else {
                            $edad = $fechanacString->diff($hoy)->y;
                        }
                        echo " - " . $edad . " años";
                        ?>
                    </span>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $numdoc = $form->get('numdoc')->setValue($persona->getNumeroDocumento())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($numdoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $tipodoc = $form->get('tipodoc')->setValue($persona->getTipoDocumento())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($tipodoc);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $nombres = $form->get('nombre')->setValue($persona->getNombres())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $nombres->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($nombres);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $apellidos = $form->get('apellido')->setValue($persona->getApellidos())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $apellidos->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($apellidos);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        if (($cola->getIdpersona()->getFechanacimiento()) == NULL) {
                                            $fechanac = $form->get('fechanac')->setValue($persona->getFechanacimiento())->setAttribute("disabled", true);
                                        } else {
                                            $fechanac = $form->get('fechanac')->setValue($persona->getFechanacimiento()->format("d/m/Y"))->setAttribute("disabled", true);
                                        }
                                        echo $formLabel->openTag() . $fechanac->getOption('label') . " ";
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($fechanac);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label>Edad</label>
                                        <input name="edad" type="text" value="<?php echo $edad; ?>" class="form-control" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $sexo = $form->get('sexo')->setValue($persona->getSexo())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formRadio($sexo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $lgbti = $form->get('lgbti')->setValue($persona->getLgbti())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $lgbti->getOption('label') . $formLabel->closeTag() . "</br>";
                                        echo $this->formRadio($lgbti);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $anonimo = $form->get('checkbox')->setValue($persona->getAnonimo())->setAttributes(array('id' => 'anonimo', 'name' => 'anonimo', 'disabled' => true));
                                        echo $formLabel->openTag() . $anonimo->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($anonimo);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-file"></i>
                    <h3 class="box-title">Hechos</h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <span class="description">
                        <?php
                        echo $expediente->getFechahechos()->format("d/m/Y");
                        echo " - ";
                        echo $expediente->getDeptohechos()->getNombre();
                        echo " - ";
                        echo $expediente->getMunihechos()->getNombre();
                        ?>
                    </span>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $fecha = $form->get('fechahecho')->setValue($expediente->getFechahechos()->format("d/m/Y"))->setAttributes(array("type" => "date", "class" => "form-control datepicker", "readonly" => false, "required" => true));
                                echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $area = $form->get('areaubicacion')->setValue($expediente->getArea())->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $area->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($area);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $direccion = $form->get('direccion')->setValue($expediente->getLugarhechos());
                                echo $formLabel->openTag() . $direccion->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($direccion);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $deptos = $this->deptos;
                                $deptosOptions = array();
                                foreach ($deptos as $deptoOption) {
                                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                }
                                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($expediente->getMunihechos())->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($depto);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $munis = $this->munis;
                                //print_r($munis);
                                $munisOptions = array();
                                foreach ($munisOptions as $muniOption) {
                                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                }
                                $muni = $form->get('muni')->setValueOptions($deptosOptions)->setValue($expediente->getMunihechos())->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($muni);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $hechos = $form->get('descripcionhechos')->setValue($expediente->getHechos())->setAttributes(array("id" => "hechos", "required" => true));
                                echo $formLabel->openTag() . $hechos->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($hechos);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $peticion = $form->get('peticion')->setValue($expediente->getPeticion());
                                echo $formLabel->openTag() . $peticion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($peticion);
                                ?>
                            </div>
                        </div>
                        <div class = "col-xs-6">
                            <div class="form-group">
                                <?php
                                $pruebas = $form->get('pruebas')->setValue($expediente->getPruebas());
                                echo $formLabel->openTag() . $pruebas->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($pruebas);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="box box-default color-palette-box collapsed-box" id = "calificacion">
                <div class="box-header with-border">
                    <i class="fa fa-check-circle"></i>
                    <h3 class="box-title">Calificación de Derechos</h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <span class="description">
                        <?php
                        echo ucwords(strtolower($expediente->getIdTipo()->getTipo()));
                        ?>
                    </span>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $tipoexpediente = $form->get('tipoexpediente')->setValue($expediente->getIdTipo()->getId())->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $tipoexpediente->getOption('label') . "  &nbsp;" . $formLabel->closeTag();
                                echo $this->formRadio($tipoexpediente);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <strong>Hechos violatorios</strong>
                            <ul>
                                <?php
                                foreach ($calificacion as $hecho) {
                                    echo "<li>" . $hecho->getIdHecho()->getHecho() . "</li>";
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-check-circle"></i>
                    <h3 class="box-title">Detalle de Orientación</h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Minimizar">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $detalleorientacion = $form->get('detalleorientacion')->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $detalleorientacion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($detalleorientacion);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $remision = $form->get('remision')->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $remision->getOption('label') . " &nbsp; " . $formLabel->closeTag();
                                echo $this->formRadio($remision);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row collapse" id="instremision">
                        <div class="col-xs-4">
                            <h4>Sector</h4>
                            <div class="form-group">
                                <?php
                                //$lugarremision = $form->get('lugarremision')->setAttributes(array("required" => true));
                                //echo $formLabel->openTag() . $lugarremision->getOption('label') . $formLabel->closeTag();
                                //echo $this->formText($lugarremision);
                                /* $instituciones = $this->institucion;
                                  foreach ($instituciones as $institucionOption) {
                                  $institucion = $form->get('institucion[]')->setLabel($institucionOption->getNombre());
                                  /* echo "<div class='checkbox'>";
                                  echo $formLabel->openTag();
                                  echo $this->formCheckbox($derecho);
                                  echo $derecho->getLabel('label');
                                  echo $formLabel->closeTag();
                                  echo "</div>";
                                  echo "<div class='checkbox'>";
                                  echo "<label><input type='checkbox' name='institucion[]' value='" . $institucionOption->getId() . "'>";
                                  echo $institucionOption->getNombre() . "</label></div>";
                                  } */
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <h4>Instituciones</h4>
                            <div class="form-group" id="instdependientes">

                            </div>
                        </div>
                        <div class="col-xs-4">
                            <h4>Remisiones</h4>
                            <div id="resumenremision" class="padding-lg">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <?php
        echo $this->formElement($form->get('cancelar'));
        echo $this->formElement($form->get('guardar')
                        ->setLabel('Siguiente <i class="glyphicon glyphicon-chevron-right"></i>')
                        ->setAttributes(array("class" => "btn btn-primary btn-flat pull-right")));
        ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>