<?php
$expediente = $this->expediente["datos"];
$cola = $expediente->getIdCola();
$persona = $this->expediente["persona"];
$calificacion = $this->expediente["calificacion"];
$orientacion = $this->orientacion;
$remisiones = $this->remisiones;
?>
<section class="content-header">
    <h1><?php echo ucwords(strtolower($expediente->getIdTipo()->getTipo())); ?> #<?php echo $expediente->getNumero(); ?></h1>
    <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Hechos / Calificación) Etapa 1 de 3</span>
        </div>
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Orientación / Remisión) Etapa 2 de 3</span>
        </div>
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 34%">
            <span>(Resumen / Impresión) Etapa 3 de 3</span>
        </div>
    </div>
</section>
<section class="content">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url('recepcion', array('action' => 'guardarorientacion')),
        'method' => 'post'
    ));
    echo $this->form()->openTag($form);
    $formLabel = $this->plugin('formLabel');

    $idcola = $form->get('id')->setValue($cola->getId())->setAttributes(array("name" => "idcola"));
    echo $this->formInput($idcola);

    $idexpediente = $form->get('id')->setValue($expediente->getId())->setAttributes(array("name" => "idexpediente", "disabled" => true));
    echo $this->formInput($idexpediente);

    $idpersona = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array("name" => "idpersona", "disabled" => true));
    echo $this->formInput($idpersona);

    $idorientacion = $form->get('id')->setValue($orientacion->getId())->setAttributes(array("name" => "idorientacion", "disabled" => true));
    echo $this->formInput($idorientacion);

    $ide = $form->get('id')->setValue($expediente->getId())->setAttributes(array("name" => "ide", "disabled" => false));
    echo $this->formInput($ide);

    $idp = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array("name" => "idp", "disabled" => false));
    echo $this->formInput($idp);

    $ido = $form->get('id')->setValue($orientacion->getId())->setAttributes(array("name" => "ido", "disabled" => false));
    echo $this->formInput($ido);
    ?>
    <div class="row">
        <div class = "col-xs-6">
            <!------------- Inicia formulario solicitud ----------------->
            <div class = "box box-default color-palette-box collapsed-box">
                <div class = "box-header with-border">
                    <i class = "fa fa-file"></i>
                    <h3 class = "box-title">Solicitud
                        <small>
                            <?php
                            echo " / " . $cola->getFechaentrada()->format("d/m/Y H:i:s");
                            switch ($cola->getPrioridad()) {
                                case '1':
                                    $class = "red-text";
                                    $prioridad = "Urgente";
                                    break;
                                case '2':
                                    $class = "yellow-text";
                                    $prioridad = "Importante";
                                    break;
                                case '3':
                                    $class = "green-text";
                                    $prioridad = "Normal";
                            }
                            echo " / " . $prioridad;
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class = "box-body">
                    <div class = "row">
                        <div class = "col-xs-12">
                            <div class="form-group">
                                <?php
                                $fechasol = $form->get('fecha')->setValue($cola->getFechaentrada()->format("d/m/Y H:i:s"))->setAttributes(array(
                                    "name" => "fechasol",
                                    "type" => "text",
                                    "class" => "form-control datepicker",
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $fechasol->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechasol);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $prioridad = $form->get('prioridad')->setValue($cola->getPrioridad())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($prioridad);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $lapiceroverde = $form->get('lapiceroverde')->setValue($cola->getLapiceroverde())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($lapiceroverde);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $obs = $form->get('obs')->setValue($cola->getObservaciones())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($obs);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!------------- Finaliza formulario solicitud ----------------->
        </div>
        <div class="col-xs-6">
            <!---------------------- Inicia formulario de solicitante -------------------------->
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Solicitante
                        <small>
                            <?php
                            echo " / " . $persona->getNombres() . " " . $persona->getApellidos();
                            $fechanacString = $persona->getFechanacimiento();
                            $hoy = new DateTime('today');
                            if ($fechanacString == NULL) {
                                $edad = "";
                            } else {
                                $edad = $fechanacString->diff($hoy)->y;
                            }
                            echo " / " . $edad . " años";
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $anonimo = $form->get('checkbox')->setValue($persona->getAnonimo())->setAttributes(array(
                                            'id' => 'anonimo',
                                            'name' => 'anonimo',
                                            'disabled' => true
                                        ));
                                        echo $formLabel->openTag() . $anonimo->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($anonimo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $numdoc = $form->get('numdoc')->setValue($persona->getNumeroDocumento())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($numdoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $tipodoc = $form->get('tipodoc')->setValue($persona->getTipoDocumento())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($tipodoc);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $nombres = $form->get('nombre')->setValue($persona->getNombres())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $nombres->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($nombres);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $apellidos = $form->get('apellido')->setValue($persona->getApellidos())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $apellidos->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($apellidos);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        if (($cola->getIdpersona()->getFechanacimiento()) == NULL) {
                                            $fechanac = $form->get('fechanac')->setValue($persona->getFechanacimiento())->setAttribute("disabled", true);
                                        } else {
                                            $fechanac = $form->get('fechanac')->setValue($persona->getFechanacimiento()->format("d/m/Y"))->setAttribute("disabled", true);
                                        }
                                        echo $formLabel->openTag() . $fechanac->getOption('label') . " ";
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($fechanac);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label>Edad</label>
                                        <input name="edad" type="text" value="<?php echo $edad; ?>" class="form-control" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $sexo = $form->get('sexo')->setValue($persona->getSexo())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formRadio($sexo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $lgbti = $form->get('lgbti')->setValue($persona->getLgbti())->setAttribute("disabled", true);
                                        echo $formLabel->openTag() . $lgbti->getOption('label') . $formLabel->closeTag() . "</br>";
                                        echo $this->formRadio($lgbti);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">
                    <a href="#" data-toggle="" data-tt="tooltip" title="Editar" id="editarsolicitante">
                        <span class="badge bg-red"><i class="fa fa-edit"></i> Editar</span>
                    </a>
                </div>
            </div>
            <!------------- Finaliza formulario solicitante ----------------->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <!------------- Inicia formulario hechos ----------------->
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-calendar"></i>
                    <h3 class="box-title">Hechos y Calificación
                        <small>
                            <?php
                            echo " / " . $expediente->getFechahechos()->format("d/m/Y");
                            echo " / " . $expediente->getDeptohechos()->getNombre();
                            echo " / " . $expediente->getMunihechos()->getNombre();
                            echo " / " . ucwords(strtolower($expediente->getIdTipo()->getTipo()));
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $fecha = $form->get('fechahecho')->setValue($expediente->getFechahechos()->format("d/m/Y"))->setAttributes(array(
                                    "type" => "text",
                                    "class" => "form-control datepicker",
                                    "readonly" => false,
                                    "disabled" => true,
                                    "required" => true
                                ));
                                echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $area = $form->get('areaubicacion')->setValue($expediente->getArea())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $area->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($area);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $direccion = $form->get('direccion')->setValue($expediente->getLugarhechos())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $direccion->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($direccion);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">

                                <?php
                                $deptos = $this->deptos;
                                $deptosOptions = array();
                                foreach ($deptos as $deptoOption) {
                                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                }
                                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($expediente->getDeptohechos()->getCodigo())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($depto);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $munis = $this->munis;
                                //print_r($munis);
                                $munisOptions = array();
                                foreach ($munis as $muniOption) {
                                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                }
                                $muni = $form->get('muni')->setValueOptions($munisOptions)->setValue($expediente->getMunihechos()->getCodigo())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($muni);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $hechos = $form->get('deschechos')->setValue($expediente->getHechos())->setAttributes(array(
                                    "id" => "hechos",
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $hechos->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($hechos);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $peticion = $form->get('peticion')->setValue($expediente->getPeticion())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $peticion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($peticion);
                                ?>
                            </div>
                        </div>
                        <div class = "col-xs-6">
                            <div class="form-group">
                                <?php
                                $pruebas = $form->get('pruebas')->setValue($expediente->getPruebas())->setAttributes(array(
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $pruebas->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($pruebas);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="calificacion">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $tipoexpediente = $form->get('tipoexpediente')->setValue($expediente->getIdTipo()->getId())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $tipoexpediente->getOption('label') . "  &nbsp;" . $formLabel->closeTag();
                                echo $this->formRadio($tipoexpediente);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12 calificacion">
                            <strong>Hechos violatorios</strong>
                            <ul>
                                <?php
                                foreach ($calificacion as $hecho) {
                                    echo "<li>" . $hecho->getIdHecho()->getHecho() . "</li>";
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="col-xs-12 calificacion" style="display: none">
                            <div class="row">
                                <div class="col-xs-3">
                                    <h4>Civíles y Políticos</h4>
                                    <div class="form-group">
                                        <?php
                                        $derechos = $this->derechos;
                                        foreach ($derechos as $derechoOption) {
                                            if ($derechoOption->getArea() == "DCP") {
                                                $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                                echo "<div class='checkbox'>";
                                                echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                                echo $derechoOption->getDerecho() . "</label></div>";
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Económicos, Sociales y Culturales</h4>
                                    <div class="form-group checkdiv">
                                        <?php
                                        foreach ($derechos as $derechoOption) {
                                            if ($derechoOption->getArea() == "DESC") {
                                                $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                                echo "<div class='checkbox'>";
                                                echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                                echo $derechoOption->getDerecho() . "</label></div>";
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Hechos violatorios</h4>
                                    <div class="form-group" id="hechosviolatorios">
                                        <?php
                                        foreach ($calificacion as $hecho) {
                                            echo "<div class='checkbox'>";
                                            echo "<label><input type='checkbox' name ='hechos[]' checked='checked' value='" . $hecho->getIdHecho()->getId() . "'>";
                                            echo $hecho->getIdHecho()->getHecho() . "</label></div>";
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <h4>Calificación</h4>
                                    <div id="resumen" class="padding-lg">
                                        <span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">
                    <a href="#" data-toggle="" data-tt="tooltip" title="Editar" id="editarhechos">
                        <span class="badge bg-red"><i class="fa fa-edit"></i> Editar</span>
                    </a>
                </div>
            </div>
            <!------------- Finaliza formulario hechos ----------------->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <!------------- Inicia formulario orientacion ----------------->
            <div class="box box-default color-palette-box collapsed-box">
                <div class="box-header with-border">
                    <i class="fa fa-compass"></i>
                    <h3 class="box-title">Orientación y Remisiones
                        <small>
                            <?php
                            echo " / " . $orientacion->getDetalle();
                            echo " / ";
                            foreach ($remisiones as $remision) {
                                echo "<span>" . $remision->getIdInstitucion()->getInstitucion() . " - </span>";
                            }
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $detalleorientacion = $form->get('detalleorientacion')->setValue($orientacion->getDetalle())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $detalleorientacion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($detalleorientacion);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $remision = $form->get('remision')->setValue($orientacion->getRemite())->setAttributes(array(
                                    "required" => true,
                                    "disabled" => true
                                ));
                                echo $formLabel->openTag() . $remision->getOption('label') . " &nbsp; " . $formLabel->closeTag();
                                echo $this->formRadio($remision);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="remisiones">
                        <div class="col-xs-12 remisiones">
                            <strong>Remisiones</strong>
                            <ul>
                                <?php
                                foreach ($remisiones as $remision) {
                                    echo "<li>" . $remision->getIdInstitucion()->getInstitucion() . "</li>";
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="col-xs-12 remisiones" style="display: none">
                            <div class="row">
                                <div class="col-xs-4">
                                    <h4>Sector</h4>
                                    <div class="form-group">
                                        <?php
                                        $instituciones = $this->institucion;
                                        foreach ($instituciones as $institucionOption) {
                                            $institucion = $form->get('institucion[]')->setLabel($institucionOption->getNombre());
                                            echo "<div class='checkbox'>";
                                            echo "<label><input type='checkbox' name='institucion[]' value='" . $institucionOption->getId() . "'>";
                                            echo $institucionOption->getNombre() . "</label></div>";
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-4">
                                    <h4>Instituciones</h4>
                                    <div class="form-group" id="instdependientes">
                                        <?php
                                        foreach ($remisiones as $remision) {
                                            echo "<div class='checkbox'>";
                                            echo "<label><input type='checkbox' name ='instdependientes[]' checked='checked' value='" . $remision->getIdInstitucion()->getId() . "'>";
                                            echo $remision->getIdInstitucion()->getInstitucion() . "</label></div>";
                                        }
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-4">
                                    <h4>Remisiones</h4>
                                    <div id="resumenremision" class="padding-lg">
                                        <span></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">
                    <a href="#" data-toggle="" data-tt="tooltip" title="Editar" id="editarorientacion">
                        <span class="badge bg-red"><i class="fa fa-edit"></i> Editar</span>
                    </a>
                </div>
            </div>
            <!------------- Finaliza formulario orientacion ----------------->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-files-o"></i>
                    <h3 class="box-title">Documentos
                        <small>
                            <?php
                            $docs = $this->docs;
                            $count = count($docs);
                            echo "El expediente tiene (" . $count . ") documentos";
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body table-responsive no-padding">
                    <?php
                    if ($count > 0) {
                        $value = false;
                        echo "<table class='table table-hover'>"
                        . "<tbody>"
                        . "<tr>"
                        . "<th>Fecha</th>"
                        . "<th>Nombre</th>"
                        . "<th>Descargar</th>"
                        . "</tr>";
                        foreach ($docs as $doc) {
                            echo "<tr>";
                            echo "<td>" . $doc->getFecha()->format("d/m/Y") . "</td>";
                            echo "<td>" . $doc->getIdAccion()->getAccion() . "</td>";
                            echo "<td><a href='" . $this->basePath() . $doc->getUbicacion() . "' target='_blank'>" . $doc->getIdAccion()->getAccion() . "<a></td>";
                            echo "<tr>";
                        }
                        echo "</tbody>"
                        . "</table>";
                    } else {
                        $value = true;
                        echo "<div class='col-xs-12 text-center'>"
                        . "<span class='text-muted'>Aún no existe ningún documento</span>"
                        . "</div>";
                    }
                    ?>
                </div>
            </div>
        </div>

    </div>
    <div class="box-footer">
        <?php
        if ($this->flashMessenger()->hasMessages()) {

            echo '<div class="alert-message alert alert-success alert-dismissible fade in" role="alert">';
            echo '<button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"><span aria-hidden="true">×</span></button>';
            $messages = $this->flashMessenger()->getMessages();
            foreach ($messages as $message) {
                echo $message;
            }

            echo '</div>';
        }
        $url = $this->url;

        echo $this->formElement($form->get('guardar'));
        echo "<a href='" . $url . "' class='btn btn-default btn-flat'><i class='glyphicon glyphicon-print'></i> Generar PDF</a>";
        echo $this->formElement($form->get('siguiente')
                        ->setLabel("Terminar")
                        ->setAttributes(array(
                            "type" => "button",
                            "disabled" => $value,
                            "onclick" => 'window.location="' . $this->basePath() . '/recepcion/terminar/' . $expediente->getId() . '"'
        )));
        ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>
<script>

    $('#recepcion').submit(validateDerecho);
    $('#recepcion').submit(validateinstitucion);
</script>