<?php $visita = $this->visita; ?>
<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Salida de visita</h3>
                </div>
                <div class="box-body">
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttributes(array(
                        'action' => $this->url('recepcion', array('action' => 'salidat', 'id' => $this->id)),
                        'method' => 'post'
                    ));

                    // Get the form label plugin
                    $formLabel = $this->plugin('formLabel');
                    // Render the opening tag
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $fecha_actual = date("Y-m-d");
                                //echo $fecha_actual;
                                $fecha = $form->get('fecha')->setValue($fecha_actual);
                                echo $formLabel->openTag() . $fecha->getOption('label') . " ";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $hora_actual = date("H:i:s");
                                //echo $hora_actual;
                                $hora = $form->get('hora')->setValue($hora_actual);
                                echo $formLabel->openTag() . $hora->getOption('label') . " ";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formInput($hora);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $obs = $form->get('obs');
                                echo $formLabel->openTag() . $obs->getOption('label') . " ";

                                //echo $this->formElementErrors($name);
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($obs);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <?php echo $this->formElement($form->get('guardar')) ?>
                        <button class="btn btn-danger btn-flat" data-dismiss="modal">Cancelar</button>
                    </div>
                    <?php echo $this->form()->closeTag() ?>

                </div>

            </div>
        </div>
    </div>
</section>



