<section class="content-header">
    <h1>Solicitud #<?php echo $cola->getId(); ?></h1>
    <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
            <span>(Hechos / Calificación) Etapa 1 de 3</span>
        </div>
    </div>
</section>
<section class="content">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action' => $this->url('recepcion', array('action' => 'guardarsolicitud')),
        'method' => 'post',
        'data-toggle' => 'validator'
    ));
    echo $this->form()->openTag($form);
    $formLabel = $this->plugin('formLabel');

    $id = $form->get('id')->setValue($cola->getId());
    echo $this->formInput($id);

    $idpersona = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array(
        "name" => "idpersona",
        "disabled" => false
    ));
    echo $this->formInput($idpersona);

    $idp = $form->get('id')->setValue($cola->getIdpersona()->getId())->setAttributes(array(
        "name" => "idp",
        "disabled" => false
    ));
    echo $this->formInput($idp);
    ?>
    <div class="row">
        <div class="col-xs-12">
            <div class = "box box-default color-palette-box collapsed-box">
                <div class = "box-header with-border">
                    <i class = "fa fa-file"></i>
                    <h3 class = "box-title">Solicitud
                        <small>
                            <?php
                            echo " / " . $cola->getFechaentrada()->format("d/m/Y H:i:s");
                            switch ($cola->getPrioridad()) {
                                case '1':
                                    $class = "red-text";
                                    $prioridad = "Urgente";
                                    break;
                                case '2':
                                    $class = "yellow-text";
                                    $prioridad = "Importante";
                                    break;
                                case '3':
                                    $class = "green-text";
                                    $prioridad = "Normal";
                            }
                            echo " / " . $prioridad;
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class = "row">
                        <div class = "col-xs-12">
                            <div class="form-group">
                                <?php
                                $fechasol = $form->get('fechasol')->setValue($cola->getFechaentrada()->format("d/m/Y H:i:s"))->setAttributes(array("type" => "date", "class" => "form-control datepicker", "disabled" => true));
                                echo $formLabel->openTag() . $fechasol->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fechasol);
                                ?>

                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $prioridad = $form->get('prioridad')->setValue($cola->getPrioridad())->setAttributes(array("disabled" => true));
                                echo "<p>" . $formLabel->openTag() . $prioridad->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($prioridad);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $lapiceroverde = $form->get('lapiceroverde')->setValue($cola->getLapiceroverde())->setAttributes(array("disabled" => true));
                                echo "<p>" . $formLabel->openTag() . $lapiceroverde->getOption('label');
                                echo $formLabel->closeTag() . "</p>";
                                echo $this->formRadio($lapiceroverde);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $obs = $form->get('obs')->setValue($cola->getObservaciones())->setAttributes(array("disabled" => true));
                                echo $formLabel->openTag() . $obs->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($obs);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <!---------------------- Inicia formulario de solicitante -------------------------->
            <div class="box box-default color-palette-box ">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Solicitante
                        <small>
                            <?php
                            echo " / " . $cola->getIdpersona()->getNombres() . " " . $cola->getIdpersona()->getApellidos();
                            $fechanacString = $cola->getIdpersona()->getFechanacimiento();
                            $hoy = new DateTime('today');
                            if ($fechanacString == NULL) {
                                $edad = "";
                            } else {
                                $edad = $fechanacString->diff($hoy)->y;
                            }
                            echo " / " . $edad . " años";
                            ?>
                        </small>
                    </h3>
                    <div class="pull-right">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Maximizar">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body" id="denunciante">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $anonimo = $form->get('checkbox')->setValue($cola->getIdpersona()->getAnonimo())->setAttributes(array(
                                    'id' => 'anonimo',
                                    'name' => 'solicitante_anonimo'
                                ));
                                echo $formLabel->openTag() . $anonimo->getOption('label') . $formLabel->closeTag();
                                echo "  " . $this->formInput($anonimo);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $numdoc = $form->get('numdoc')->setValue($cola->getIdpersona()->getNumeroDocumento())->setAttributes(array(
                                            "name" => "solicitante_numdoc"
                                        ));
                                        echo $formLabel->openTag() . $numdoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($numdoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $tipodoc = $form->get('tipodoc')->setValue($cola->getIdpersona()->getTipoDocumento())->setAttributes(array(
                                            "name" => "solicitante_tipodoc"
                                        ));
                                        ;
                                        echo $formLabel->openTag() . $tipodoc->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($tipodoc);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $nombres = $form->get('nombre')->setValue($cola->getIdpersona()->getNombres())->setAttributes(array(
                                            "name" => "solicitante_nombre"
                                        ));
                                        echo $formLabel->openTag() . $nombres->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($nombres);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $apellidos = $form->get('apellido')->setValue($cola->getIdpersona()->getApellidos())->setAttributes(array(
                                            "name" => "solicitante_apellido"
                                        ));
                                        echo $formLabel->openTag() . $apellidos->getOption('label') . $formLabel->closeTag();
                                        echo $this->formInput($apellidos);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        if (($cola->getIdpersona()->getFechanacimiento()) == NULL) {
                                            $value = $cola->getIdpersona()->getFechanacimiento();
                                        } else {
                                            $value = $cola->getIdpersona()->getFechanacimiento()->format("d/m/Y");
                                        }
                                        $fechanac = $form->get('fechanac')->setValue($value)->setAttributes(array(
                                            "name" => "solicitante_fechanac"
                                        ));
                                        echo $formLabel->openTag() . $fechanac->getOption('label') . " ";
                                        echo $formLabel->closeTag();
                                        echo $this->formInput($fechanac);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $edad = $form->get('edad')->setValue($cola->getIdpersona()->getEdad())->setAttributes(array(
                                            "name" => "solicitante_edad",
                                            "id" => "solicitante_edad"
                                        ));
                                        echo $formLabel->openTag() . $edad->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formNumber($edad);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $sexo = $form->get('sexo')->setValue($cola->getIdpersona()->getSexo())->setAttributes(array(
                                            "name" => "solicitante_sexo"
                                        ));
                                        echo $formLabel->openTag() . $sexo->getOption('label') . $formLabel->closeTag() . "<br>";
                                        echo $this->formRadio($sexo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $lgbti = $form->get('lgbti')->setValue($cola->getIdpersona()->getLgbti())->setAttributes(array(
                                            "name" => "solicitante_lgbti"
                                        ));
                                        echo $formLabel->openTag() . $lgbti->getOption('label') . $formLabel->closeTag() . "</br>";
                                        echo $this->formRadio($lgbti);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $correo = $form->get('correo')->setValue($cola->getIdpersona()->getCorreoElectronico())->setAttributes(array(
                                            "name" => "solicitante_correo"
                                        ));
                                        echo $formLabel->openTag() . $correo->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formEmail($correo);
                                        echo $this->formElementErrors($correo);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $telefono = $form->get('telefono')->setValue($cola->getIdpersona()->getTelefono())->setAttributes(array(
                                            "name" => "solicitante_telefono"
                                        ));
                                        echo $formLabel->openTag() . $telefono->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($telefono);
                                        echo $this->formElementErrors($telefono);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <?php
                                        $direccionden = $form->get('direccion')->setValue($cola->getIdpersona()->getDireccion())->setAttributes(array(
                                            "name" => "solicitante_direccion",
                                            "required" => true
                                        ));
                                        echo $formLabel->openTag() . $direccionden->getOption('label') . $formLabel->closeTag();
                                        echo "  " . $this->formInput($direccionden);
                                        echo $this->formElementErrors($direccionden);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $deptos = $this->deptos;
                                        $deptosOptions = array();
                                        if (($cola->getIdpersona()->getDepto()) == NULL) {
                                            $deptoValue = NULL;
                                        } else {
                                            $deptoValue = $cola->getIdpersona()->getDepto()->getCodigo();
                                        }

                                        foreach ($deptos as $deptoOption) {
                                            $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                        }
                                        $depto = $form->get('depto')->setValueOptions($deptosOptions)->setValue($deptoValue)->setAttributes(array(
                                            "name" => "solicitante_depto",
                                            "required" => true,
                                            "disabled" => false
                                        ));
                                        echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($depto);
                                        ?>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <?php
                                        $munis = $this->munis;
                                        $munisOptions = array();
                                        if (($cola->getIdpersona()->getMuni()) == NULL) {
                                            $muniValue = NULL;
                                        } else {
                                            $muniValue = $cola->getIdpersona()->getMuni()->getCodigo();
                                        }
                                        foreach ($munis as $muniOption) {
                                            $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                        }
                                        $muni = $form->get('muni')->setValueOptions($munisOptions)->setValue($muniValue)->setAttributes(array(
                                            "name" => "solicitante_muni",
                                            "required" => true,
                                            "disabled" => false
                                        ));
                                        echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                        echo $this->formSelect($muni);
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix">

                </div>
            </div>
            <!------------- Finaliza formulario solicitante ----------------->
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <!---------------------- Inicia formulario de hechos -------------------------->
            <div class="box box-default color-palette-box">
                <div class="box-header with-border">
                    <i class="fa fa-file"></i>
                    <h3 class="box-title">Hechos</h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Minimizar">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $fecha = $form->get('fechahecho')->setAttributes(array(
                                    "name" => "hechos_fecha",
                                    "required" => true));
                                echo $formLabel->openTag() . $fecha->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($fecha);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $area = $form->get('areaubicacion')->setAttributes(array(
                                    "name" => "hechos_ubicacion"
                                ));
                                echo $formLabel->openTag() . $area->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($area);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $direccion = $form->get('direccion')->setAttributes(array(
                                    "name" => "hechos_direccion"
                                ));
                                echo $formLabel->openTag() . $direccion->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formInput($direccion);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $deptos = $this->deptos;
                                $deptosOptions = array();
                                foreach ($deptos as $deptoOption) {
                                    $deptosOptions[$deptoOption->getCodigo()] = $deptoOption->getNombre();
                                }
                                $depto = $form->get('depto')->setValueOptions($deptosOptions)->setAttributes(array(
                                    "name" => "hechos_depto",
                                    "required" => true
                                ));
                                echo $formLabel->openTag() . $depto->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($depto);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $munis = $this->munis;
                                $munisOptions = array();
                                foreach ($munis as $muniOption) {
                                    $munisOptions[$muniOption->getCodigo()] = $muniOption->getNombre();
                                }
                                $muni = $form->get('muni')->setValueOptions($munisOptions)->setAttributes(array(
                                    "name" => "hechos_muni",
                                    "required" => true
                                ));
                                echo $formLabel->openTag() . $muni->getOption('label') . $formLabel->closeTag();
                                echo $this->formSelect($muni);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $hechos = $form->get('deschechos')->setAttributes(array(
                                    "name" => "hechos_descripcion",
                                    "id" => "hechos",
                                    "required" => true));
                                echo $formLabel->openTag() . $hechos->getOption('label') . " ";
                                echo $formLabel->closeTag();
                                echo $this->formTextarea($hechos);
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group">
                                <?php
                                $peticion = $form->get('peticion')->setAttributes(array(
                                    "name" => "hechos_peticion"
                                ));
                                echo $formLabel->openTag() . $peticion->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($peticion);
                                ?>
                            </div>
                        </div>
                        <div class = "col-xs-6">
                            <div class="form-group">
                                <?php
                                $pruebas = $form->get('pruebas')->setAttributes(array(
                                    "name" => "hechos_pruebas"
                                ));
                                echo $formLabel->openTag() . $pruebas->getOption('label') . $formLabel->closeTag();
                                echo $this->formTextarea($pruebas);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!---------------------- Inicia formulario de solicitante -------------------------->
        </div>
    </div>
    <div class = "row">
        <div class = "col-xs-12">
            <!---------------------- Inicia formulario de calificacion -------------------------->
            <div class = "box box-default color-palette-box">
                <div class = "box-header with-border">
                    <i class = "fa fa-check-circle"></i>
                    <h3 class = "box-title">Calificación de Derechos</h3>
                    <div class="pull-right box-tools">
                        <a href="#" data-widget="collapse" data-tt="tooltip" title="Minimizar">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?php
                                $tipoexpediente = $form->get('tipoexpediente')->setAttributes(array("required" => true));
                                echo $formLabel->openTag() . $tipoexpediente->getOption('label') . "  &nbsp;" . $formLabel->closeTag();
                                echo $this->formRadio($tipoexpediente);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row collapse" id="calificacion">
                        <div class="col-xs-3">
                            <h4>Civíles y Políticos</h4>
                            <div class="form-group">
                                <?php
                                $derechos = $this->derechos;
                                foreach ($derechos as $derechoOption) {
                                    if ($derechoOption->getArea() == "DCP") {
                                        $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                        echo "<div class='checkbox'>";
                                        echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                        echo $derechoOption->getDerecho() . "</label></div>";
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <h4>Económicos, Sociales y Culturales</h4>
                            <div class="form-group checkdiv">
                                <?php
                                foreach ($derechos as $derechoOption) {
                                    if ($derechoOption->getArea() == "DESC") {
                                        $derecho = $form->get('derecho[]')->setLabel($derechoOption->getDerecho());
                                        echo "<div class='checkbox'>";
                                        echo "<label><input type='checkbox' name='derecho[]' value='" . $derechoOption->getId() . "'>";
                                        echo $derechoOption->getDerecho() . "</label></div>";
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <h4>Hechos violatorios</h4>
                            <div class="form-group" id="hechosviolatorios">

                            </div>
                        </div>
                        <div class="col-xs-3">
                            <h4>Calificación</h4>
                            <div id="resumen" class="padding-lg">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!---------------------- Inicia formulario de solicitante -------------------------->
        </div>
    </div>
    <div class="box-footer">
        <?php
        echo $this->formElement($form->get('siguiente'));
        ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script>
    $('#recepcion').submit(validateDerecho);
</script>