<meta http-equiv="refresh" content="30"/>
<section class="content-header">
    <h1>Recepción de personas</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Registro de visitas</h3>
                </div>
                <div class="box-body">
                    <table id="datatable" class="table table-bordered table-hover table-responsive dataTable" cellspacing="0">

                        <thead>
                            <tr>
                                <th></th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Empresa / Institución</th>
                                <th>Hora</th>
                                <th>Empleado</th>
                                <th>Extensión</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $visitas = $this->visitas;


                            foreach ($visitas as $visita):

                                $call = $visita->getLlamadasRealizadas();

                                switch ($call) {
                                    case (0):
                                        $style = "white-text";
                                        break;
                                    case (1 && $call < 3):
                                        $style = "badge badge-notify bg-green";
                                        break;
                                    case (3 && $call < 5):
                                        $style = "badge badge-notify bg-orange";
                                        break;
                                    case ($call >= 5):
                                        $style = "badge badge-notify bg-red";
                                        break;
                                }
                                ?>
                                <tr>
                                    <td class="notifications-menu">
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'hacellamada', 'id' => $visita->getId())); ?>">
                                            <span class="fa fa-phone fa-lg black-text"></span>
                                            <span class="<?php echo $style; ?>"><?php echo $call; ?></span>
                                        </a>
                                    </td>
                                    <td>
                                        <?php echo $visita->getIdpersona()->getNombres(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getIdpersona()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getInstitucion(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getFechaentrada()->format('H:i:s'); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getEmpleado()->getNombres() . " " . $visita->getEmpleado()->getApellidos(); ?>
                                    </td>
                                    <td>
                                        <?php echo $visita->getEmpleado()->getExtension(); ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'detallevisita', 'id' => $visita->getId())); ?>" data-toggle="modal" data-target="#detailsModal">
                                            <span class="badge bg-blue">Detalle</span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'editarvisita', 'id' => $visita->getId())); ?>">
                                            <span class="badge bg-orange">Editar</span>
                                        </a>
                                        <a href="<?php echo $this->url('recepcion', array('action' => 'salidavisita', 'id' => $visita->getId())); ?>" data-toggle="modal" data-target="#departureModal">
                                            <span class="badge bg-red">Retirar</span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!--fab-button-add-->
<div class="fixed-action-btn">
    <nav class="fab">
        <?php
        $permisos = $this->permisos;
        foreach ($permisos as $permiso) {
            foreach ($permiso["permiso"] as $perm) {
                if ($perm == 11) {
                    echo "<a class='fab-button bg-primary " . $permiso["accion"] . "' href='" . $this->url('recepcion', array('action' => 'registro', 'id' => $permiso["accion"])) . "' data-tip='tooltip' title='" . ucfirst($permiso["accion"]) . "'>";
                }
            }
        }
        ?>
        <a class="fab-button" href="#"><span class="fab-span"><span class="fab-span rotate"></span></span></a>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<div class="modal fade" id="departureModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">


        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({

        });
    });
</script>