<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!--Sidebar user panel (optional) -->
        <div class = "user-panel">
            <div class = "pull-left image">
                <img src = "<?php echo $this->basePath() . '/img/avatars/user32.png' ?>" class = "img-circle" alt = "User Image">
            </div>
            <div class = "pull-left info">
                <p><?php echo $this->identity->getUsuario(); ?></p>
                <!--Status -->
                <a href = "#"><i class = "fa fa-circle text-success"></i> En linea</a>
            </div>
        </div>

        <!--search form (Optional) -->
        <!--<form action = "#" method = "get" class = "sidebar-form">
        <div class = "input-group">
        <input type = "text" name = "q" class = "form-control" placeholder = "Buscar...">
        <span class = "input-group-btn">
        <button type = "submit" name = "search" id = "search-btn" class = "btn btn-flat"><i class = "fa fa-search"></i>
        </button>
        </span>
        </div>
        </form>
        <!--/.search form -->

        <!--Sidebar Menu -->
        <ul class = "sidebar-menu">
            <li class = "header">Menú principal</li>
            <!--Optionally, you can add icons to the links -->
            <li><a href = "<?php echo $this->url('recepcion') ?>/visita"><i class = "glyphicon glyphicon-user"></i><span><?php echo $this->translate('Registro de visitas')
?></span></a></li>
            <li><a href="<?php echo $this->url('recepcion') ?>/cola"><i class="glyphicon glyphicon-edit"></i><span>Cola de solicitantes</span></a></li>
            <li><a href="<?php echo $this->url('recepcion') ?>/consulta"><i class="glyphicon glyphicon-link"></i><span>Consulta de expedientes</span></a></li>
            <li><a href="<?php echo $this->url('recepcion') ?>/buscar"><i class="glyphicon glyphicon-search"></i><span>Buscar personas</span></a></li>
            <!--<li class="treeview">
              <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
              </ul>
            </li>-->
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>