<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!--Sidebar user panel (optional) -->
        <div class = "user-panel">
            <div class = "pull-left image">
                <img src = "<?php echo $this->basePath() . '/img/avatars/user32.png' ?>" class = "img-circle" alt = "User Image">
            </div>
            <div class = "pull-left info">
                <p><?php echo $this->identity->getUsuario(); ?></p>
                <p><?php echo ucwords(strtolower($this->identity->getIdEmpleado()->getIdsede()->getNombre())); ?></p>
                <!--Status -->
                <a href = "#"><i class = "fa fa-circle text-success"></i> En linea</a>
            </div>
        </div>

        <!--search form (Optional) -->
        <!--<form action = "#" method = "get" class = "sidebar-form">
        <div class = "input-group">
        <input type = "text" name = "q" class = "form-control" placeholder = "Buscar...">
        <span class = "input-group-btn">
        <button type = "submit" name = "search" id = "search-btn" class = "btn btn-flat"><i class = "fa fa-search"></i>
        </button>
        </span>
        </div>
        </form>
        <!--/.search form -->
        <!--Sidebar Menu -->
        <ul class = "sidebar-menu">
            <li class = "header">Menú principal</li>
            <!--Optionally, you can add icons to the links -->
            <li><a href = "<?php echo $this->url('recepcion', array('action' => 'visita')) ?>"><i class = "glyphicon glyphicon-user"></i><span><?php echo $this->translate('Registro de visitas')
?></span></a></li>
            <li><a href="<?php echo $this->url('recepcion', array('action' => 'cola')) ?>"><i class="glyphicon glyphicon-edit"></i><span>Cola de solicitantes</span></a></li>
            <li><a href="<?php echo $this->url('recepcion', array('action' => 'consulta')) ?>"><i class="glyphicon glyphicon-link"></i><span>Consulta de expedientes</span></a></li>
            <li><a href="<?php echo $this->url('recepcion', array('action' => 'buscar')) ?>"><i class="glyphicon glyphicon-search"></i><span>Buscar personas</span></a></li>
            <li>
                <a href="<?php echo $this->url('recepcion', array('action' => 'incompleto')) ?>">
                    <i class="glyphicon glyphicon-unchecked"></i>
                    <span>Casos iniciados</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-red"><?php echo count($this->atendidos) ?></small>
                    </span>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('recepcion', array('action' => 'expedienteinc')) ?>">
                    <i class="glyphicon glyphicon-alert"></i>
                    <span>Casos pendientes</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-red"><?php echo count($this->iniciados) ?></small>
                    </span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>