<header class="main-header">
    <!-- Logo -->
    <a href="<?php echo $this->url('recepcion') ?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>SGI</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">Sistema de Gestión</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Centros de mensajes</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <!-- start message -->
                                <!--<li>
                                    <a href="#">
                                        <div class="pull-left">
                                <!-- User Image -->
                                <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->
                                <!--</div>
                                <!-- Message title and timestamp -->
                                <!--<h4>
                                    Remitente
                                    <small><i class="fa fa-clock-o"></i>tiempo</small>
                                </h4>
                                <!-- The message -->
                                <!--<p>Mensaje</p>
                                </a>
                                </li>
                                <!-- end message -->
                            </ul>
                            <!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">Ver todos</a></li>
                    </ul>
                </li>
                <!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <!--<span class="label label-warning">10</span>-->
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Conteo notificaciones</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <!-- start notification -->
                                <!--<li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i>notificacion
                                    </a>
                                </li>
                                <!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">Ver todas</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <!--<span class="label label-danger">9</span>-->
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Centro de tareas</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <!-- Task item -->
                                <!--<li>
                                    <a href="#">
                                <!-- Task title and progress text -->
                                <!--<h3>
                                    Nombre tarea
                                    <small class="pull-right">20%</small>
                                </h3>
                                <!-- The progress bar -->
                                <!--<div class="progress xs">
                                <!-- Change the css width attribute to simulate progress -->
                                <!--<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                    <span class="sr-only">20% Completado</span>
                                </div>
                                </div>
                                </a>
                                </li>
                                <!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">Ver todas</a>
                        </li>
                    </ul>
                </li>

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar -->
                        <img src="<?php echo $this->basePath() . '/img/avatars/user.png' ?>" class="user-image" alt="Imagen de usuario">
                        <span class="hidden-xs"><?php echo $this->identity->getUsuario(); ?></span>
                        <!-- hidden-xs hides the username on small devices so only the image appears.-->

                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="<?php echo $this->basePath() . '/img/avatars/user32.png' ?>" class="img-circle" alt="">
                            <p><?php echo $this->identity->getIdEmpleado()->getNombres() . " " . $this->identity->getIdEmpleado()->getApellidos(); ?></p>
                            <p><small><?php echo $this->identity->getIdEmpleado()->getPuesto(); ?></small></p>
                        </li>
                        <!-- Menu Body -->
                        <!--<li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        <!-- /.row -->
                        <!--</li>-->
                        <!-- Menu Footer -->
                        <li class="bg-custom1">
                            <ul class="nav nav-stacked">
                                <li><a href="<?php echo $this->url('admin', array('action' => 'perfil')); ?>"><span>Detalles de cuenta</span><i class="pull-right fa fa-info-circle"></i></a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li class="bg-red">
                    <a href="#" data-toggle="modal" data-target="#confirmModal"><i class="glyphicon glyphicon-log-out" ></i>  Salir</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

            </div>
            <div class="modal-body">
                ¿Está seguro que desea salir del sistema?

            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger pull-left" data-dismiss="modal">No</a>
                <a href="<?php echo $this->url('inicio/procesar', array('action' => 'logout')); ?>" class="btn btn-primary">Si</a>
            </div>
        </div>
    </div>
</div>