<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SGI') ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                //->prependStylesheet($this->basePath() . '/css/style.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/_all-skins.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/app.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition login-page">
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
