<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SGI') ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                //->prependStylesheet($this->basePath() . '/css/style.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/_all-skins.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                ->prependStylesheet($this->basePath() . '/css/datatables.min.css')
                ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/app.js')
                ->prependFile($this->basePath() . '/js/validator.min.js')
                ->prependFile($this->basePath() . '/js/datatables.min.js')
                //->prependFile($this->basePath() . '/js/jquery.dataTables.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/js/jquery.js')
        ;
        ?>
        <script language="javascript">
            //window.location = "page3.html"
            //window.history.forward(2);
        </script>
    </head>
    <body class="hold-transition skin-blue sidebar-collapse sidebar-mini">
        <div class="wrapper">
            <!-- Main Header -->
            <!-- Left side column. contains the logo and sidebar -->
            <?php echo $this->header; ?>
            <?php echo $this->aside; ?>
            <?php echo $this->addbutton; ?>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <!-- Main content -->
                <?php echo $this->content; ?>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="pull-right hidden-xs">
                </div>
                <!-- Default to the left -->
                <strong>&copy; 2005 - <?php echo date('Y') ?> / DT-PDH</strong> Todos los derechos reservados <?php /* echo $this->translate('All rights reserved.') */ ?>

            </footer>

            <!-- aqui va el aside derecho si se desea colocar copiarlo del template original -->
        </div>
        <!-- ./wrapper -->
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
            /*
             *  Llamado a funcion anonimo
             */
            var input = "#anonimo";
            $(input).change(function() {
                esAnonimo(input);
            });

            /*
             *  Llamado a funcion validar dpi para ver si existe en la db
             */
            $("#tipodoc").change(function() {
                validarNumdoc();
            });

            /*
             *  Llamado a funcion obtener datos segun el dpi
             */
            var url = "<?php echo $this->basePath(); ?>/validacion/validardpi";
            $("#numdoc").autocomplete({
                source: function(request, response) {
                    obtenerDatos(url, request, response);

                },
                minLength: 6
            });

            /*
             *  Llamado a funcion completar datos para llenar formulario
             */
            $("#numdoc").focusout(function() {
                var url = "<?php echo $this->basePath(); ?>/validacion/seleccionardpi";
                completarDatosDPI(url);

            });

            /*
             *  Llamado a funcion cambiar departamento para obtener municipios
             */
            $("select[name='depto']").change(function() {
                var url = "<?php echo $this->basePath(); ?>/validacion/listarmunicipios";
                var depto = $(this).val();
                cambiarDepto(url, depto);
            });

            /*
             *  Llamado a funcion cambiar unidad para obtener empleados
             */
            $("select[name='unidad']").change(function() {
                var url = "<?php echo $this->basePath(); ?>/validacion/listarempleados";
                var unidad = $(this).val();
                cambiarUnidad(url, unidad);
                /*if (($(this).val() == 0)) {

                 }*/
            });
            /*
             * Muestra y oculta calificacion
             */
            $('#editarhechos').click(function() {
                $('.calificacion').toggle();
            });
            /*
             *  Llamado a funcion calificar derecho y hecho
             */
            $("input[name='derecho[]']").click(function() {
                var url = "<?php echo $this->basePath(); ?>/validacion/listarhechos";
                var id = $(this).val();
                var comp = $("input[name='tipoexpediente']:checked").val();
                if ($(this).is(":checked")) {
                    //alert(id);
                    calificadorDerecho(url, id, comp);
                } else {
                    //alert(id);
                    $("div[data-group='" + id + "']").empty();
                }

            });
            /*
             * Muestra y oculta calificacion
             */
            $('#editarorientacion').click(function() {
                $('.remisiones').toggle();
            });

            /*
             *  Llamado a funcion checkbox instituciones
             */
            $("input[name='institucion[]']").click(function() {
                var url = "<?php echo $this->basePath(); ?>/validacion/listarinstituciones";
                var id = $(this).val();
                if ($(this).is(":checked")) {
                    checkboxInsitucion(url, id);
                } else {
                    $("div[data-group='" + id + "']").empty();
                }

            });


        </script>
        <script type="text/javascript">
            $.extend(true, $.fn.dataTable.defaults, {
                "language": {
                    "url": "<?php echo $this->basePath(); ?>/js/datatables/spanish.json",
                    "autoWidth": true
                }

            });
            $("[data-tt=tooltip]").tooltip({trigger: "hover"});
            $("[data-tip=tooltip]").tooltip({placement: "left", trigger: "hover"});
        </script>
    </body>
</html>
