<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SGI') ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                //->prependStylesheet($this->basePath() . '/css/style.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/_all-skins.css')
                ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                ->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.css')
                ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/app.js')
                ->prependFile($this->basePath() . '/js/dataTables.bootstrap.js')
                ->prependFile($this->basePath() . '/js/jquery.dataTables.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/js/jquery.js')
        ;
        ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <!-- Main Header -->
            <!-- Left side column. contains the logo and sidebar -->
            <?php echo $this->header; ?>
            <?php echo $this->aside; ?>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <!-- Main content -->
                <?php echo $this->content; ?>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="pull-right hidden-xs">
                </div>
                <!-- Default to the left -->
                <strong>&copy; 2005 - <?php echo date('Y') ?> / DT-PDH</strong> Todos los derechos reservados <?php /* echo $this->translate('All rights reserved.') */ ?>

            </footer>

            <!-- aqui va el aside derecho si se desea colocar copiarlo del template original -->
        </div>
        <!-- ./wrapper -->
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#datatable').DataTable({
                    "language": {
                        "url": "<?php echo $this->basePath(); ?>/js/datatables/spanish.json"
                    },
                    "bSort": false
                });
            });
            $("[data-tt=tooltip]").tooltip();
        </script>
    </body>
</html>
